### ISSUE TITLE
Problem: rebuild_elasticsearch_aip_index_from_files task fails in default configuration

### ISSUE THREAD

**Issue by scollazo** [artefactual/archivematica#1035]
This task fails to rebuild the aip index when the default configurations are in place.

As the AIPStore is located at  `/var/archivematica/sharedDirectory/www/AIPsStore/`, but default configuration the transferBacklog is also located there (`/var/archivematica/sharedDirectory/www/AIPsStore/transferBacklog`) , the backlogged transfers cause an error (below)

I'm unsure if this is a bug,  as the aip I had stored was reindexed, and i think  AIP folders should precede trasnsferBacklog when sorted alphabetically.

<pre>
[root@am16-centos-ansible-updated-to-1 dashboard]# /usr/share/archivematica/virtualenvs/archivematica-dashboard/bin/python manage.py rebuild_elasticsearch_aip_index_from_files /var/archivematica/sharedDirectory/www/AIPsStore/
No handlers could be found for logger "elasticsearch.trace"
Rebuilding AIPS index from AIPS in /var/archivematica/sharedDirectory/www/AIPsStore/
Processing AIP 12bb8058-7f5c-4d8b-aded-245aa1c5f29f
Command to run: ['unar', '-force-overwrite', '-o', '/tmp/tmpfImDj9', '/var/archivematica/sharedDirectory/www/AIPsStore/12bb/8058/7f5c/4d8b/aded/245a/a1c5/f29f/test-1.6-12bb8058-7f5c-4d8b-aded-245aa1c5f29f.7z', 'test-1.6-12bb8058-7f5c-4d8b-aded-245aa1c5f29f/data/METS.12bb8058-7f5c-4d8b-aded-245aa1c5f29f.xml']
/var/archivematica/sharedDirectory/www/AIPsStore/12bb/8058/7f5c/4d8b/aded/245a/a1c5/f29f/test-1.6-12bb8058-7f5c-4d8b-aded-245aa1c5f29f.7z: 7-Zip
  test-1.6-12bb8058-7f5c-4d8b-aded-245aa1c5f29f/data/METS.12bb8058-7f5c-4d8b-aded-245aa1c5f29f.xml  (135078 B)... OK.
Successfully extracted to "/tmp/tmpfImDj9/test-1.6-12bb8058-7f5c-4d8b-aded-245aa1c5f29f".
Removed FITS output from METS.
Removed FITS output from METS.
Indexed AIP files and corresponding METS XML.
Processing AIP d0192694-fe6b-4986-8a60-3de877206968
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/opt/archivematica/archivematica/src/dashboard/src/main/management/commands/rebuild_elasticsearch_aip_index_from_files.py", line 260, in handle
    delete_existing_data=options['delete'],
  File "/opt/archivematica/archivematica/src/dashboard/src/main/management/commands/rebuild_elasticsearch_aip_index_from_files.py", line 143, in processAIPThenDeleteMETSFile
    relative_path=mets_file_relative_path)
  File "/opt/archivematica/archivematica/src/dashboard/src/main/management/commands/rebuild_elasticsearch_aip_index_from_files.py", line 59, in extract_file
    shutil.copy(os.path.join(archive_path, relative_path), output_path)
  File "/usr/lib64/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/usr/lib64/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/var/archivematica/sharedDirectory/www/AIPsStore/transferBacklog/originals/backlogged-1.6-d0192694-fe6b-4986-8a60-3de877206968/data/METS.d0192694-fe6b-4986-8a60-3de877206968.xml'
</pre>

**Comment by scollazo** [comment]
Not sure if this bugs pertains here, in the docs, or in ss...

**Comment by sevein** [comment]
@jhsimpson @jrwdunham, how do you think we should fix this?
I can exclude `transferBacklog`, would that be alright?

**Comment by scollazo** [comment]
That would fix this issue, but I think we should address the root cause, and move transferBacklog  space outside of the AIPstore space

**Comment by sevein** [comment]
Tentative fix in #1039 now merged.
