### ISSUE TITLE
Problem: Ingest fails if Archivematica isn't connected to the Internet

### ISSUE THREAD

**Issue by ross-spencer** [artefactual/archivematica#1050]
To recreate: Disconnect AM from the outside world and set-off a standard Transfer. This results in a failure in storeAIP:
```
storeAIP.py: DEBUG     2018-04-09 09:07:08,767  urllib3.connectionpool:_new_conn:208:  Starting new HTTP connection (1): archivematica-storage-service
storeAIP.py: DEBUG     2018-04-09 09:07:08,824  urllib3.connectionpool:_make_request:396:  http://archivematica-storage-service:8000 "GET /api/v2/pipeline/7ba85817-2ba9-4842-b63b-7d8d0f8b925c/ HTTP/1.1" 200 None
storeAIP.py: DEBUG     2018-04-09 09:07:08,843  urllib3.connectionpool:_new_conn:208:  Starting new HTTP connection (1): archivematica-storage-service
storeAIP.py: DEBUG     2018-04-09 09:07:08,932  urllib3.connectionpool:_make_request:396:  http://archivematica-storage-service:8000 "GET /api/v2/location/?pipeline__uuid=7ba85817-2ba9-4842-b63b-7d8d0f8b925c&purpose=CP&offset=0 HTTP/1.1" 200 None
storeAIP.py: DEBUG     2018-04-09 09:07:08,988  urllib3.connectionpool:_new_conn:208:  Starting new HTTP connection (1): archivematica-storage-service
storeAIP.py: DEBUG     2018-04-09 09:07:09,050  urllib3.connectionpool:_make_request:396:  http://archivematica-storage-service:8000 "GET /api/v2/pipeline/7ba85817-2ba9-4842-b63b-7d8d0f8b925c/ HTTP/1.1" 200 None
storeAIP.py: INFO      2018-04-09 09:07:09,053  archivematica.common:create_file:305:  Creating file with {'current_path': 'offline-c9426832-68a7-4c82-ab49-072845c1e83b.7z', 'related_package_uuid': None, 'agents': [('agent', {'xsi:schema_location': 'info:lc/xmlns/premis-v2 http://www.loc.gov/standards/premis/v2/premis-v2-2.xsd', 'version': '2.2'}, ('agent_identifier', ('agent_identifier_type', u'preservation system'), ('agent_identifier_value', u'Archivematica-1.7')), ('agent_name', u'Archivematica'), ('agent_type', u'software')), ('agent', {'xsi:schema_location': 'info:lc/xmlns/premis-v2 http://www.loc.gov/standards/premis/v2/premis-v2-2.xsd', 'version': '2.2'}, ('agent_identifier', ('agent_identifier_type', u'repository code'), ('agent_identifier_value', u'test')), ('agent_name', u'test'), ('agent_type', u'organization'))], 'current_location': '/api/v2/location/default/AS/', 'size': 13943, 'origin_path': u'currentlyProcessing/offline-c9426832-68a7-4c82-ab49-072845c1e83b/offline-c9426832-68a7-4c82-ab49-072845c1e83b.7z', 'origin_pipeline': u'/api/v2/pipeline/7ba85817-2ba9-4842-b63b-7d8d0f8b925c/', 'uuid': 'c9426832-68a7-4c82-ab49-072845c1e83b', 'package_type': 'AIP', 'origin_location': u'/api/v2/location/85445e49-fabc-4409-a81f-b23759ea37ee/', 'aip_subtype': 'Archival Information Package', 'events': [('event', {'xsi:schema_location': 'info:lc/xmlns/premis-v2 http://www.loc.gov/standards/premis/v2/premis-v2-2.xsd', 'version': '2.2'}, ('event_identifier', ('event_identifier_type', 'UUID'), ('event_identifier_value', u'321c01ce-5ba0-4d79-8572-a934f9516ebc')), ('event_type', u'compression'), ('event_date_time', '2018-04-09T09:06:52.783564+00:00'), ('event_detail', u'program=7z; algorithm=bzip2; version=p7zip Version 9.20 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,4 CPUs)\n'), ('event_outcome_information', ('event_outcome', u''), ('event_outcome_detail', ('event_outcome_detail_note', u'Standard Output=""; Standard Error=""'))), ('linking_agent_identifier', ('linking_agent_identifier_type', u'preservation system'), ('linking_agent_identifier_value', u'Archivematica-1.7')), ('linking_agent_identifier', ('linking_agent_identifier_type', u'repository code'), ('linking_agent_identifier_value', u'test'))), ('event', {'xsi:schema_location': 'info:lc/xmlns/premis-v2 http://www.loc.gov/standards/premis/v2/premis-v2-2.xsd', 'version': '2.2'}, ('event_identifier', ('event_identifier_type', 'UUID'), ('event_identifier_value', u'c45392ec-467e-4460-89e6-1a051466bd31')), ('event_type', u'fixity check'), ('event_date_time', '2018-04-09T09:07:07.027540+00:00'), ('event_detail', u'program="python, bag"; module="hashlib.sha256()"'), ('event_outcome_information', ('event_outcome', u'Pass'), ('event_outcome_detail', ('event_outcome_detail_note', u'All 3 checksums generated at start of transfer match those generated by BagIt (bag).'))), ('linking_agent_identifier', ('linking_agent_identifier_type', u'preservation system'), ('linking_agent_identifier_value', u'Archivematica-1.7')), ('linking_agent_identifier', ('linking_agent_identifier_type', u'repository code'), ('linking_agent_identifier_value', u'test')))]}
storeAIP.py: DEBUG     2018-04-09 09:07:09,069  urllib3.connectionpool:_new_conn:208:  Starting new HTTP connection (1): archivematica-storage-service
storeAIP.py: DEBUG     2018-04-09 09:07:09,878  urllib3.connectionpool:_make_request:396:  http://archivematica-storage-service:8000 "POST /api/v2/file/async/ HTTP/1.1" 202 None
storeAIP.py: DEBUG     2018-04-09 09:07:09,892  urllib3.connectionpool:_new_conn:208:  Starting new HTTP connection (1): archivematica-storage-service
storeAIP.py: DEBUG     2018-04-09 09:07:09,971  urllib3.connectionpool:_make_request:396:  http://archivematica-storage-service:8000 "GET /api/v2/async/2/ HTTP/1.1" 200 None
storeAIP.py: DEBUG     2018-04-09 09:07:11,990  urllib3.connectionpool:_new_conn:208:  Starting new HTTP connection (1): archivematica-storage-service
storeAIP.py: DEBUG     2018-04-09 09:07:12,057  urllib3.connectionpool:_make_request:396:  http://archivematica-storage-service:8000 "GET /api/v2/async/2/ HTTP/1.1" 200 None
storeAIP.py: DEBUG     2018-04-09 09:07:14,073  urllib3.connectionpool:_new_conn:208:  Starting new HTTP connection (1): archivematica-storage-service
storeAIP.py: DEBUG     2018-04-09 09:07:14,135  urllib3.connectionpool:_make_request:396:  http://archivematica-storage-service:8000 "GET /api/v2/async/2/ HTTP/1.1" 200 None
storeAIP.py: WARNING   2018-04-09 09:07:14,139  archivematica.common:wait_for_async:208:  Failure storing file: <class 'lxml.etree.XMLSchemaParseError'>: Element '{http://www.w3.org/2001/XMLSchema}attributeGroup', attribute 'ref': The QName value '{http://www.w3.org/1999/xlink}simpleLink' does not resolve to a(n) attribute group definition., line 674
SIP creation failed.  See Storage Service logs for more details
<class 'lxml.etree.XMLSchemaParseError'>: Element '{http://www.w3.org/2001/XMLSchema}attributeGroup', attribute 'ref': The QName value '{http://www.w3.org/1999/xlink}simpleLink' does not resolve to a(n) attribute group definition., line 674
storeAIP.py: WARNING   2018-04-09 09:07:14,140  archivematica.mcp.client.storeAIP:store_aip:184:  SIP unabled to be created: <class 'lxml.etree.XMLSchemaParseError'>: Element '{http://www.w3.org/2001/XMLSchema}attributeGroup', attribute 'ref': The QName value '{http://www.w3.org/1999/xlink}simpleLink' does not resolve to a(n) attribute group definition., line 674.  See logs for more details.
```

**Comment by ross-spencer** [comment]
In `stable/1.7.1` we seem to have a more verbose message, containing connection failure info:
```
storeAIP.py: DEBUG     2018-07-11 12:25:33,999  urllib3.connectionpool:_new_conn:208:  Starting new HTTP connection (1): 146.141.12.31
storeAIP.py: DEBUG     2018-07-11 12:25:34,012  urllib3.connectionpool:_make_request:396:  http://146.141.12.31:8000 "GET /api/v2/pipeline/64d31ae1-3bbe-41f4-86d7-78915e3577f1/ HTTP/1.1" 200 None
storeAIP.py: DEBUG     2018-07-11 12:25:34,021  urllib3.connectionpool:_new_conn:208:  Starting new HTTP connection (1): 146.141.12.31
storeAIP.py: DEBUG     2018-07-11 12:25:34,040  urllib3.connectionpool:_make_request:396:  http://146.141.12.31:8000 "GET /api/v2/location/?pipeline__uuid=64d31ae1-3bbe-41f4-86d7-78915e3577f1&purpose=CP&offset=0 HTTP/1.1" 200 None
storeAIP.py: DEBUG     2018-07-11 12:25:34,060  urllib3.connectionpool:_new_conn:208:  Starting new HTTP connection (1): 146.141.12.31
storeAIP.py: DEBUG     2018-07-11 12:25:34,071  urllib3.connectionpool:_make_request:396:  http://146.141.12.31:8000 "GET /api/v2/pipeline/64d31ae1-3bbe-41f4-86d7-78915e3577f1/ HTTP/1.1" 200 None
storeAIP.py: INFO      2018-07-11 12:25:34,072  archivematica.common:create_file:283:  Creating file with {'current_path': 'diskimageJP-839761be-a6ce-4c28-ba43-3f54c33647a9.7z', 'related_package_uuid': None, 'agents': [('agent', {'xsi:schema_location': 'info:lc/xmlns/premis-v2 http://www.loc.gov/standards/premis/v2/premis-v2-2.xsd', 'version': '2.2'}, ('agent_identifier', ('agent_identifier_type', u'preservation system'), ('agent_identifier_value', u'Archivematica-1.7.1')), ('agent_name', u'Archivematica'), ('agent_type', u'software')), ('agent', {'xsi:schema_location': 'info:lc/xmlns/premis-v2 http://www.loc.gov/standards/premis/v2/premis-v2-2.xsd', 'version': '2.2'}, ('agent_identifier', ('agent_identifier_type', u'repository code'), ('agent_identifier_value', u'Wits id')), ('agent_name', u'Wits'), ('agent_type', u'organization')), ('agent', {'xsi:schema_location': 'info:lc/xmlns/premis-v2 http://www.loc.gov/standards/premis/v2/premis-v2-2.xsd', 'version': '2.2'}, ('agent_identifier', ('agent_identifier_type', u'Archivematica user pk'), ('agent_identifier_value', u'1')), ('agent_name', u'username="wits", first_name="", last_name=""'), ('agent_type', u'Archivematica user'))], 'current_location': '/api/v2/location/0879d578-630f-4f93-84f2-a0ea8e23d592/', 'size': 7959646, 'origin_path': u'currentlyProcessing/diskimageJP-839761be-a6ce-4c28-ba43-3f54c33647a9/diskimageJP-839761be-a6ce-4c28-ba43-3f54c33647a9.7z', 'origin_pipeline': u'/api/v2/pipeline/64d31ae1-3bbe-41f4-86d7-78915e3577f1/', 'uuid': '839761be-a6ce-4c28-ba43-3f54c33647a9', 'package_type': 'AIP', 'origin_location': u'/api/v2/location/cefb4edf-5c21-499e-9a5f-a5bcceea8f7d/', 'aip_subtype': 'Archival Information Package', 'events': [('event', {'xsi:schema_location': 'info:lc/xmlns/premis-v2 http://www.loc.gov/standards/premis/v2/premis-v2-2.xsd', 'version': '2.2'}, ('event_identifier', ('event_identifier_type', 'UUID'), ('event_identifier_value', u'fe47a228-fc14-4d99-94bb-0bcf8d39d61e')), ('event_type', u'compression'), ('event_date_time', '2018-07-11T12:24:59.439317+00:00'), ('event_detail', u'program=7z; algorithm=bzip2; version=p7zip Version 9.20 (locale=en_ZA.UTF-8,Utf16=on,HugeFiles=on,8 CPUs)\n'), ('event_outcome_information', ('event_outcome', u''), ('event_outcome_detail', ('event_outcome_detail_note', u'Standard Output=""; Standard Error=""'))), ('linking_agent_identifier', ('linking_agent_identifier_type', u'preservation system'), ('linking_agent_identifier_value', u'Archivematica-1.7.1')), ('linking_agent_identifier', ('linking_agent_identifier_type', u'repository code'), ('linking_agent_identifier_value', u'Wits id')), ('linking_agent_identifier', ('linking_agent_identifier_type', u'Archivematica user pk'), ('linking_agent_identifier_value', u'1')))]}
storeAIP.py: DEBUG     2018-07-11 12:25:34,077  urllib3.connectionpool:_new_conn:208:  Starting new HTTP connection (1): 146.141.12.31
storeAIP.py: DEBUG     2018-07-11 12:25:36,119  urllib3.connectionpool:_make_request:396:  http://146.141.12.31:8000 "POST /api/v2/file/ HTTP/1.1" 500 None
storeAIP.py: WARNING   2018-07-11 12:25:36,121  archivematica.common:create_file:296:  Unable to create file from {'current_path': 'diskimageJP-839761be-a6ce-4c28-ba43-3f54c33647a9.7z', 'related_package_uuid': None, 'agents': [('agent', {'xsi:schema_location': 'info:lc/xmlns/premis-v2 http://www.loc.gov/standards/premis/v2/premis-v2-2.xsd', 'version': '2.2'}, ('agent_identifier', ('agent_identifier_type', u'preservation system'), ('agent_identifier_value', u'Archivematica-1.7.1')), ('agent_name', u'Archivematica'), ('agent_type', u'software')), ('agent', {'xsi:schema_location': 'info:lc/xmlns/premis-v2 http://www.loc.gov/standards/premis/v2/premis-v2-2.xsd', 'version': '2.2'}, ('agent_identifier', ('agent_identifier_type', u'repository code'), ('agent_identifier_value', u'Wits id')), ('agent_name', u'Wits'), ('agent_type', u'organization')), ('agent', {'xsi:schema_location': 'info:lc/xmlns/premis-v2 http://www.loc.gov/standards/premis/v2/premis-v2-2.xsd', 'version': '2.2'}, ('agent_identifier', ('agent_identifier_type', u'Archivematica user pk'), ('agent_identifier_value', u'1')), ('agent_name', u'username="wits", first_name="", last_name=""'), ('agent_type', u'Archivematica user'))], 'current_location': '/api/v2/location/0879d578-630f-4f93-84f2-a0ea8e23d592/', 'size': 7959646, 'origin_path': u'currentlyProcessing/diskimageJP-839761be-a6ce-4c28-ba43-3f54c33647a9/diskimageJP-839761be-a6ce-4c28-ba43-3f54c33647a9.7z', 'origin_pipeline': u'/api/v2/pipeline/64d31ae1-3bbe-41f4-86d7-78915e3577f1/', 'uuid': '839761be-a6ce-4c28-ba43-3f54c33647a9', 'package_type': 'AIP', 'origin_location': u'/api/v2/location/cefb4edf-5c21-499e-9a5f-a5bcceea8f7d/', 'aip_subtype': 'Archival Information Package', 'events': [('event', {'xsi:schema_location': 'info:lc/xmlns/premis-v2 http://www.loc.gov/standards/premis/v2/premis-v2-2.xsd', 'version': '2.2'}, ('event_identifier', ('event_identifier_type', 'UUID'), ('event_identifier_value', u'fe47a228-fc14-4d99-94bb-0bcf8d39d61e')), ('event_type', u'compression'), ('event_date_time', '2018-07-11T12:24:59.439317+00:00'), ('event_detail', u'program=7z; algorithm=bzip2; version=p7zip Version 9.20 (locale=en_ZA.UTF-8,Utf16=on,HugeFiles=on,8 CPUs)\n'), ('event_outcome_information', ('event_outcome', u''), ('event_outcome_detail', ('event_outcome_detail_note', u'Standard Output=""; Standard Error=""'))), ('linking_agent_identifier', ('linking_agent_identifier_type', u'preservation system'), ('linking_agent_identifier_value', u'Archivematica-1.7.1')), ('linking_agent_identifier', ('linking_agent_identifier_type', u'repository code'), ('linking_agent_identifier_value', u'Wits id')), ('linking_agent_identifier', ('linking_agent_identifier_type', u'Archivematica user pk'), ('linking_agent_identifier_value', u'1')))]} because 500 Server Error: INTERNAL SERVER ERROR for url: http://146.141.12.31:8000/api/v2/file/
SIP creation failed. See Storage Service logs for more details.
500 Server Error: INTERNAL SERVER ERROR for url: http://146.141.12.31:8000/api/v2/file/
storeAIP.py: WARNING   2018-07-11 12:25:36,121  archivematica.mcp.client.storeAIP:store_aip:194:  Unable to create SIP: 500 Server Error: INTERNAL SERVER ERROR for url: http://146.141.12.31:8000/api/v2/file/. See Storage Service logs for more details.
```

**Comment by ross-spencer** [comment]
**NB** It looks like these maybe two separate issues, so will separate them out as soon as i have confirmed one or two things with our devops team. I am currently trying to understand the impact of the proxy changes on the API connection to the storage service when AM would have connected to the SS to display transfers in the transfer browser. Info on how the proxy was set up to resolve the second issue here: https://projects.artefactual.com/issues/12273

**Comment by ablwr** [comment]
:pray: :pray: :pray:

**Comment by ross-spencer** [comment]
Okay, the response from the LOC website for http://www.loc.gov/standards/mets/version111/mets.xsd today looks like this:

![image](https://user-images.githubusercontent.com/1880412/46637856-af4aaa00-cb23-11e8-9c49-11ffc226ee5d.png)

And if we CURL:

```
 curl -v http://www.loc.gov/standards/mets/version111/mets.xsd
*   Trying 104.16.55.16...
* TCP_NODELAY set
* Connected to www.loc.gov (104.16.55.16) port 80 (#0)
> GET /standards/mets/version111/mets.xsd HTTP/1.1
> Host: www.loc.gov
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 302 Object Moved
< Date: Mon, 08 Oct 2018 22:58:12 GMT
< Content-Type: text/html
< Transfer-Encoding: chunked
< Connection: keep-alive
< Set-Cookie: __cfduid=d1b3669e09322aa8ee88b6a781c8209b11539039492; expires=Tue, 08-Oct-19 22:58:12 GMT; path=/; domain=.loc.gov; HttpOnly
< Location: https://www.loc.gov/search/500/
< Cache-Control: private
< Server: cloudflare
< CF-RAY: 466c35fc20b49b6f-DFW
< 
* Connection #0 to host www.loc.gov left intact
<head><body> This object may be found <a HREF="https://www.loc.gov/search/500/">here</a> </body>
```

Which results in the following in AM:

```
storeaip_v0.0: WARNING   2018-10-08 22:54:19,860  archivematica.mcp.client.storeAIP.store_aip:215  SIP creation failed: Failure storing file: <class 'lxml.etree.XMLSchemaParseError'>: Element '{http://www.w3.org/2001/XMLSchema}attributeGroup', attribute 'ref': The QName value '{http://www.w3.org/1999/xlink}simpleLink' does not resolve to a(n) attribute group definition., line 674.
SIP creation failed: Failure storing file: <class 'lxml.etree.XMLSchemaParseError'>: Element '{http://www.w3.org/2001/XMLSchema}attributeGroup', attribute 'ref': The QName value '{http://www.w3.org/1999/xlink}simpleLink' does not resolve to a(n) attribute group definition., line 674. See logs for more details.Traceback (most recent call last):
  File "/src/MCPClient/lib/job.py", line 102, in JobContext
    yield
  File "/src/MCPClient/lib/clientScripts/store_aip.py", line 313, in call
    args.sip_uuid, args.sip_name, args.sip_type))
  File "/src/MCPClient/lib/clientScripts/store_aip.py", line 216, in store_aip
    raise Exception(errmsg + " See logs for more details.")
Exception: SIP creation failed: Failure storing file: <class 'lxml.etree.XMLSchemaParseError'>: Element '{http://www.w3.org/2001/XMLSchema}attributeGroup', attribute 'ref': The QName value '{http://www.w3.org/1999/xlink}simpleLink' does not resolve to a(n) attribute group definition., line 674. See logs for more details.
```

This is actually a storage service error, and the full version is as follows:

```
archivematica-storage-service_1  | ERROR     2018-10-08 15:26:29  locations.models.async_manager:async_manager:wrapper:122:  Task threw an error: Element '{http://www.w3.org/2001/XMLSchema}attributeGroup', attribute 'ref': The QName value '{http://www.w3.org/1999/xlink}simpleLink' does not resolve to a(n) attribute group definition., line 674
archivematica-storage-service_1  | Traceback (most recent call last):
archivematica-storage-service_1  |   File "/src/storage_service/locations/models/async_manager.py", line 119, in wrapper
archivematica-storage-service_1  |     value = task_fn(*args, **kwargs)
archivematica-storage-service_1  |   File "/src/storage_service/locations/api/resources.py", line 701, in task
archivematica-storage-service_1  |     self._store_bundle(bundle)
archivematica-storage-service_1  |   File "/src/storage_service/locations/api/resources.py", line 675, in _store_bundle
archivematica-storage-service_1  |     premis_agents=agents, aip_subtype=aip_subtype)
archivematica-storage-service_1  |   File "/src/storage_service/locations/models/package.py", line 608, in store_aip
archivematica-storage-service_1  |     premis_agents=premis_agents, aip_subtype=aip_subtype)
archivematica-storage-service_1  |   File "/src/storage_service/locations/models/package.py", line 794, in _store_aip_ensure_pointer_file
archivematica-storage-service_1  |     premis_agents=premis_agents, aip_subtype=aip_subtype)
archivematica-storage-service_1  |   File "/src/storage_service/locations/models/package.py", line 824, in _create_pointer_file_write_to_disk
archivematica-storage-service_1  |     package_subtype=aip_subtype)
archivematica-storage-service_1  |   File "/src/storage_service/locations/models/package.py", line 1243, in create_pointer_file
archivematica-storage-service_1  |     pointer_file.serialize(), schematron=metsrw.AM_PNTR_SCT_PATH)
archivematica-storage-service_1  |   File "/usr/local/lib/python2.7/site-packages/metsrw/validate.py", line 45, in validate
archivematica-storage-service_1  |     is_xsd_valid, xsd_error_log = xsd_validate(mets_doc, xmlschema=xmlschema)
archivematica-storage-service_1  |   File "/usr/local/lib/python2.7/site-packages/metsrw/validate.py", line 94, in xsd_validate
archivematica-storage-service_1  |     xmlschema = get_xmlschema(xmlschema, mets_doc)
archivematica-storage-service_1  |   File "/usr/local/lib/python2.7/site-packages/metsrw/validate.py", line 90, in get_xmlschema
archivematica-storage-service_1  |     return etree.XMLSchema(xmlschema)
archivematica-storage-service_1  |   File "src/lxml/xmlschema.pxi", line 87, in lxml.etree.XMLSchema.__init__ (src/lxml/lxml.etree.c:196372)
archivematica-storage-service_1  | XMLSchemaParseError: Element '{http://www.w3.org/2001/XMLSchema}attributeGroup', attribute 'ref': The QName value '{http://www.w3.org/1999/xlink}simpleLink' does not resolve to a(n) attribute group definition., line 674
```

Which can be traced back to the validation step in `package.py:create_pointer_file(...)` here: https://github.com/artefactual/archivematica-storage-service/blob/07ae87501b93f4c917f1c0a49dc76ba5c369039d/storage_service/locations/models/package.py#L1241-L1248

Once commented out, the transfer passes successfully. 

What is interesting about the problem here is that we only expect a warning from the storage service, yet, because we don't handle the exception, we cause store_aip.py to fail entirely. The main impact to this is on indexing, and in the user interface where the ingest fails. 

![image](https://user-images.githubusercontent.com/1880412/46637967-3730b400-cb24-11e8-86db-314cb826aa6f.png)

We should be able to handle the exception in the storage service and validation can fail, but perhaps in a non-breaking way.

**Comment by ablwr** [comment]
Nice detailed research @ross-spencer !!!

**Comment by ross-spencer** [comment]
Thx @ablwr !! :+1: :+1: :+1:

**Comment by sallain** [comment]
This looks fixed to me! @mamedin disabled the DNS for one of our test servers and I was able to ingest and store a package as expected. The only microservice that did not work was Upload DIP which was an expected failure,  one that I enacted purely to ensure that the connection was indeed down. I think we can call this fixed.

**Comment by sallain** [comment]
Added to release notes; no documentation needed, I think.
