### ISSUE TITLE
 Problem: file not found error during parse_dataverse

### ISSUE THREAD

**Issue by ross-spencer** [artefactual/archivematica#1120]
Logging this for the OCUL work in case we can do a bit more bullet-proofing. The following error seems to appear if the `parse_dataverse.py` script fails previously. 

**Standard output (stdout)**
```
Parse Dataverse METS
looking again
Could not find Drinks/Drinks.tab in database
Look for Drinks.tab
```
**Standard error (stderr)**
```
Traceback (most recent call last):
  File "/src/MCPClient/lib/clientScripts/parse_dataverse.py", line 193, in <module>
    sys.exit(main(args.transfer_dir, args.transfer_uuid))
  File "/src/MCPClient/lib/clientScripts/parse_dataverse.py", line 178, in main
    mapping = get_db_objects(mets, unit_uuid)
  File "/src/MCPClient/lib/clientScripts/parse_dataverse.py", line 47, in get_db_objects
    f = models.File.objects.get(originallocation__endswith=bname, transfer_id=transfer_uuid)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
main.models.DoesNotExist: File matching query does not exist.
```
Similar perhaps to https://github.com/JiscRDSS/rdss-archivematica/issues/83

**Comment by ross-spencer** [comment]
Closing in favor of: https://github.com/artefactual/archivematica/issues/1148
