### ISSUE TITLE
Problem: Parse Dataverse Mets fails for some datasets

### ISSUE THREAD

**Issue by joel-simpson** [artefactual/archivematica#1148]
Testing the new "Parse Dataverse  Mets" job within the "Parse External Files" microservice. 

When testing with datasets I added to Dataverse, this job completes successfully. 

When testing datasests created by the Scholar's Portal team, this job is failing. 
![screen shot 2018-06-20 at 10 07 14 am](https://user-images.githubusercontent.com/17187309/41663623-d9a5d85a-7471-11e8-9af3-7c4161ec2850.png)

The error message from the task that doesn't complete is: 
![screen shot 2018-06-20 at 10 07 41 am](https://user-images.githubusercontent.com/17187309/41663649-ea0b5a08-7471-11e8-984b-3e8cc716e474.png)

I am not sure if it is relevant, but to get to access this dataset, I used "data&subtree=archivematica" in the relative path of the Dataverse location. For the datasets that have passed this job, that field is only set to "archivematica".

**Comment by joel-simpson** [comment]
The following dataset from the Archivematica Test Dataverse fails at the Parse Dataverse Mets microservice: 
[3D Laser Images of a road cut at Ivy Lea, Ontario (2007), underground in Sudbury, Ontario (2007), underground in Thompson, Manitoba (2009) [test]](https://demodv.scholarsportal.info/dataset.xhtml?persistentId=doi:10.5072/FK2/HAQQUC)

**Comment by ross-spencer** [comment]
Discussing this last-week with a Kaitlin at OCUL, it was noted that to include a ZIP file in a Dataverse is a deliberate decision by the researcher because Dataverse will automatically extract the first level of zips that it comes across.

From: http://guides.dataverse.org/en/latest/user/dataset-management.html
> Compressed Files
Compressed files in zip format are unpacked automatically. If it fails to unpack, for whatever reason, it will upload as is. If the number of files inside are more than a set limit (1,000), you will get an error message and the file will uploads as is.

Support for unpacking tar files will be added when this ticket is closed: https://github.com/IQSS/dataverse/issues/2195.

While more testing about how to include ZIPs inside a Dataverse might be useful, for example, to confirm if it is still possible, and to document that. It is likely that this issue will be resolved by the creation of a new micro-service that will unzip the dataset that is downloaded from Dataverse (or a modification to the extract-packages micro-service to avoid recursive unzipping given a Dataverse transfer type.) The chain-links in the former example will no-longer have an 'Extract Packages' microservice and the behaviour will need documenting.

**Comment by joel-simpson** [comment]
I have confirmed that of the 4 datasets we've manage to successfully create AIPs with, none have zip files included. Also worth noting that only 2 of the test datasets provided by the SP team have zip files. 

I don't think this is essential to fix at this stage (so I have NOT added the 1.8 milestone) but I do think we need to document this constraint better before we put this back into the backlog (i.e. why is it that a zip file makes the "parase dataverse" job fail). For now am leaving this in 'refining' status.

**Comment by joel-simpson** [comment]
I have retested this with the latest development branches (SS [PR 398](https://github.com/artefactual/archivematica-storage-service/pull/398) and AM PR #1242). It is still the case that the job "Parse Dataverse METS"  is failing when a ZIP package is included in the dataset, and the choice to extract packages is set to 'yes'. (If a dataset includes a zip but extract packages is set to 'no', processing completes successfully). 

Here is the error output when we include a ZIP in the dataset, extract the package and "delete packages after extraction" is set to NO. 
```
parsedataverse: INFO      2018-08-22 23:07:28,560  archivematica.mcp.client.parse_dataverse_mets.parse_dataverse_mets:238  Parse Dataverse METS with dir args: '/var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/extractPackagesChoice/Joel_Ziptest2-11959b4f-313b-47e1-98f2-a329fe2e90dc/' and transfer uuid: 11959b4f-313b-47e1-98f2-a329fe2e90dc
[Errno 21] Is a directory: u'/var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/extractPackagesChoice/Joel_Ziptest2-11959b4f-313b-47e1-98f2-a329fe2e90dc/objects/SeveralDatafiles.zip'Traceback (most recent call last):
  File "/src/MCPClient/lib/job.py", line 102, in JobContext
    yield
  File "/src/MCPClient/lib/clientScripts/parse_dataverse_mets.py", line 250, in call
    job.set_status(parse_dataverse_mets(job.args))
  File "/src/MCPClient/lib/clientScripts/parse_dataverse_mets.py", line 239, in parse_dataverse_mets
    return parse_(transfer_dir, transfer_uuid)
  File "/src/MCPClient/lib/clientScripts/parse_dataverse_mets.py", line 226, in parse_
    validate_checksums(mapping, unit_path)
  File "/src/MCPClient/lib/clientScripts/parse_dataverse_mets.py", line 167, in validate_checksums
    date=date,
  File "/src/MCPClient/lib/clientScripts/parse_dataverse_mets.py", line 189, in verify_checksum
    generated_checksum = get_file_checksum(path, checksumtype)
  File "/src/archivematicaCommon/lib/archivematicaFunctions.py", line 185, in get_file_checksum
    with open(filename, 'rb') as file_:
IOError: [Errno 21] Is a directory: u'/var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/extractPackagesChoice/Joel_Ziptest2-11959b4f-313b-47e1-98f2-a329fe2e90dc/objects/SeveralDatafiles.zip'
```
Here is the error output when we extract the packages, and we delete them after ("Delete packages after extraction" is set to YES.)
```
parsedataverse: INFO      2018-08-23 00:23:31,159  archivematica.mcp.client.parse_dataverse_mets.parse_dataverse_mets:238  Parse Dataverse METS with dir args: '/var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/extractPackagesChoice/Zip3_extractAndDelete-940b58e9-34a5-4866-b2ef-b9a5260d322f/' and transfer uuid: 940b58e9-34a5-4866-b2ef-b9a5260d322f
'NoneType' object has no attribute 'replace'Traceback (most recent call last):
  File "/src/MCPClient/lib/job.py", line 102, in JobContext
    yield
  File "/src/MCPClient/lib/clientScripts/parse_dataverse_mets.py", line 250, in call
    job.set_status(parse_dataverse_mets(job.args))
  File "/src/MCPClient/lib/clientScripts/parse_dataverse_mets.py", line 239, in parse_dataverse_mets
    return parse_(transfer_dir, transfer_uuid)
  File "/src/MCPClient/lib/clientScripts/parse_dataverse_mets.py", line 226, in parse_
    validate_checksums(mapping, unit_path)
  File "/src/MCPClient/lib/clientScripts/parse_dataverse_mets.py", line 163, in validate_checksums
    path=f.currentlocation.replace(
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by ross-spencer** [comment]
Hi @joel-simpson can you narrow this down to specific datasets? or provide other examples of datasets with zips that are failing? 152 Forward Sortation area is one I was looking at previously and thought I had success with. Unfortunately this isn't working on the qa server tonight - an SSL error connecting to Dataverse - but maybe one that can be tried locally?

**Comment by joel-simpson** [comment]
sure @ross-spencer... I should have listed these to start with. 
I was testing [Js_ZipInsideZiptest ](https://demodv.scholarsportal.info/dataset.xhtml?persistentId=doi:10.5072/FK2/SZ2HI4)
It passes if you don't extract the zip files, but fails if you do. 
I tested the ForwardStation dataset and the same thing happens... it flies through if you don't extract packages, but fails at Parse Dataverse METS if you do (with the following error): 
```
parsedataverse: INFO      2018-08-23 13:37:03,524  archivematica.mcp.client.parse_dataverse_mets.parse_dataverse_mets:238  Parse Dataverse METS with dir args: '/var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/extractPackagesChoice/ForwardStation_withExtraction-b923e9c6-fcc4-4aed-af93-0bd82b4f1ba2/' and transfer uuid: b923e9c6-fcc4-4aed-af93-0bd82b4f1ba2
parsedataverse: INFO      2018-08-23 13:37:03,558  archivematica.mcp.client.parse_dataverse_mets.get_db_objects:53  Could not find file type: 'Item' in the database: GBR_adm1/GBR_adm1-ddi.xml
parsedataverse: INFO      2018-08-23 13:37:03,562  archivematica.mcp.client.parse_dataverse_mets.get_db_objects:53  Could not find file type: 'Item' in the database: GBR_adm2/GBR_adm2citation-ris.ris
parsedataverse: INFO      2018-08-23 13:37:03,565  archivematica.mcp.client.parse_dataverse_mets.get_db_objects:56  Multiple entries for `TermsAndConditions.html` found. Exception: get() returned more than one File -- it returned 6!
parsedataverse: INFO      2018-08-23 13:37:03,567  archivematica.mcp.client.parse_dataverse_mets.get_db_objects:76  Multiple entries for `TermsAndConditions.html` found. Exception: get() returned more than one File -- it returned 6!
parsedataverse: ERROR     2018-08-23 13:37:03,567  archivematica.mcp.client.parse_dataverse_mets.parse_:220  Exiting. Returning the database objects for our Dataverse files has failed.
``` 
FYI - The two OCUL datasets with Zip files are 
[A/V and large size files](https://demodv.scholarsportal.info/dataset.xhtml?persistentId=doi:10.5072/FK2/6PVAY7) - which is currently not starting as a transfer due to [issue 113](https://github.com/archivematica/Issues/issues/113)
and
[3D Laser Images](https://demodv.scholarsportal.info/dataset.xhtml?persistentId=doi:10.5072/FK2/HAQQUC). This passes through Transfer stage if you don't extract packages... I'm just testing it now to see what happens if you extract packages. It's a big one so takes a long time... for now I'm going to assume it fails there too but will come back and update if I'm wrong.

**Comment by joel-simpson** [comment]
Just to confirm, 3D lasers also fails if you extract packages, with the following error (v. similar to above): 
```
parsedataverse: INFO      2018-08-23 13:54:42,495  archivematica.mcp.client.parse_dataverse_mets.parse_dataverse_mets:238  Parse Dataverse METS with dir args: '/var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/extractPackagesChoice/3DLasersWithExtraction-3efb5569-2d52-4fd3-ac15-5e640961e8cf/' and transfer uuid: 3efb5569-2d52-4fd3-ac15-5e640961e8cf
parsedataverse: INFO      2018-08-23 13:54:42,534  archivematica.mcp.client.parse_dataverse_mets.get_db_objects:56  Multiple entries for `Thompson2.jpg` found. Exception: get() returned more than one File -- it returned 4!
parsedataverse: INFO      2018-08-23 13:54:42,535  archivematica.mcp.client.parse_dataverse_mets.get_db_objects:76  Multiple entries for `Thompson2.jpg` found. Exception: get() returned more than one File -- it returned 4!
parsedataverse: ERROR     2018-08-23 13:54:42,535  archivematica.mcp.client.parse_dataverse_mets.parse_:220  Exiting. Returning the database objects for our Dataverse files has failed.
```

**Comment by ross-spencer** [comment]
It looks like the problems here are to do with what Parse Dataverse METS is capable of expecting. There are two issues I can see at present. 

1. If a package is deleted after extraction, we need to identify that it has been removed and not try to verify its checksum again. Once corrected we then need to then need to check the AIP METS is correct (and the SIP mets before that).

2. The `parse_dataverse_mets.py` code doesn't have a great awareness of where it should be finding objects in the transfer. See this extract here: https://github.com/artefactual/archivematica/blob/561fc381071fe5a2a6a0cda5145f4e7ca142fff2/src/MCPClient/lib/clientScripts/parse_dataverse_mets.py#L45-L77 the lines of code attempt to find our objects in two different ways. I believe we can make this robust by generating a path based on `"%transferDirectory%objects"` so any base_path attached to that will match with an entry in the database where an example table might look like the following for a given transfer:
```
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| originalLocation                                                                                                                                                   |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| %transferDirectory%objects/a00000002.gdbtable                                                                                                                      |
| %transferDirectory%objects/Regions.zip                                                                                                                             |
| %transferDirectory%objects/Regions_December_2015_Generalised_Clipped_Boundaries_in_England.zip/Regions_December_2015_Generalised_Clipped_Boundaries_in_England.cpg |
| %transferDirectory%objects/a00000007.CatRelTypesByDestItemTypeID.atx                                                                                               |
| %transferDirectory%objects/Regions2015GenClipEofEng.zip/Regions_December_2015_Generalised_Clipped_Boundaries_in_England.prj                                        |
| %transferDirectory%objects/a00000001.freelist                                                                                                                      |
| %transferDirectory%objects/england_nhscr_2013.zip/england_nhscr_2013.shx                                                                                           |
| %transferDirectory%objects/a00000005.CatItemTypesByName.atx                                                                                                        |
| %transferDirectory%objects/Regions_December_2015_Generalised_Clipped_Boundaries_in_England.zip/Regions_December_2015_Generalised_Clipped_Boundaries_in_England.dbf |
| %transferDirectory%objects/GBR_adm0citation-endnote.xml                                                                                                            |
| %transferDirectory%objects/england_ccg_2013.zip                                                                                                                    |
| %transferDirectory%objects/england_gor_2001.zip/england_gor_2001.sbx                                                                                               |
| %transferDirectory%objects/wales_ol_2001.zip/wales_ol_2001.sbn                                                                                                     |
| %transferDirectory%objects/al_ta_on_shp_eng.zip/CCG_BSC_Apr2015.KML                                                                                                |
| %transferDirectory%objects/England_ccg_2013.zip/england_ccg_2013.shp                                                                                               |
| %transferDirectory%objects/GBR_adm_shp.zip                                                                                                                         |
| %transferDirectory%objects/a00000006.gdbtablx                                                                                                                      |
| %transferDirectory%objects/a00000003.gdbtablx                                                                                                                      |
| %transferDirectory%objects/GBR_adm1.zip/GBR_adm1.shp                                                                                                               |
| %transferDirectory%objects/England_ccg_2013.zip                                                                                                                    |
| %transferDirectory%objects/England_nhscr_2013.zip/england_nhscr_2013.shx                                                                                           |
| %transferDirectory%objects/wales_ol_2001.zip                                                                                                                       |
| %transferDirectory%objects/GBR_adm2.zip/GBR_adm2.shx                                                                                                               |
| %transferDirectory%objects/Regions2015GenClipEofEng.zip/Regions_December_2015_Generalised_Clipped_Boundaries_in_England.cpg                                        |
| %transferDirectory%objects/soils.zip/england_nhsat_2013.shp                                                                                                        |
| %transferDirectory%objects/gfsa000b11a_e.shp                                                                                                                       |
| %transferDirectory%objects/Regions2015GenClipEofEng.zip/Regions_December_2015_Generalised_Clipped_Boundaries_in_England.xml                                        |
| %transferDirectory%objects/GBR_adm1.zip/GBR_adm1.prj                                                                                                               |
| %transferDirectory%objects/a00000004.CatItemsByPhysicalName.atx                                                                                                    |
| %transferDirectory%objects/england_ccg_2013.zip/england_ccg_2013.prj                                                                                               |
| %transferDirectory%objects/timestamps                                                                                                                              |
| %transferDirectory%objects/a0000000a.gdbindexes                                                                                                                    |
| %transferDirectory%objects/soils.zip/england_nhsat_2013.prj                                                                                                        |
| %transferDirectory%objects/a00000006.freelist                                                                                                                      |
| %transferDirectory%objects/england_nhsat_2013.zip/england_nhsat_2013.dbf                                                                                           |
| %transferDirectory%objects/a00000001.gdbtable                                                                                                                      |
| %transferDirectory%objects/GBR_adm0citation-bib.bib                                                                                                                |
| %transferDirectory%objects/Regions2015GenClipEofEng.zip/Regions_December_2015_Generalised_Clipped_Boundaries_in_England.shp                                        |
| %transferDirectory%objects/GBR_adm1citation-endnote.xml                                                                                                            |
| %transferDirectory%objects/GBR_adm1.zip                                                                                                                            |
| %transferDirectory%objects/a00000004.CatItemsByType.atx                                                                                                            |
| %transferDirectory%objects/wales_ol_2001.zip/wales_ol_2001.shx                                                                                                     |
| %transferDirectory%objects/a00000003.gdbindexes                                                                                                                    |
| %transferDirectory%objects/a00000004.freelist                                                                                                                      |
| %transferDirectory%objects/GBR_adm2.zip                                                                                                                            |
| %transferDirectory%objects/england_ccg_2013.zip/england_ccg_2013.shx                                                                                               |
| %transferDirectory%objects/a00000007.CatRelTypesByName.atx                                                                                                         |
| %transferDirectory%objects/England_ccg_2013.zip/TermsAndConditions.html                                                                                            |
| %transferDirectory%objects/Wales_ol_2001.zip                                                                                                                       |
| %transferDirectory%objects/England_nhscr_2013.zip/TermsAndConditions.html                                                                                          |
| %transferDirectory%objects/GBR_adm2.zip/GBR_adm2.shp                                                                                                               |
| %transferDirectory%objects/England_ccg_2013.zip/england_ccg_2013.dbf                                                                                               |
| %transferDirectory%objects/Regions2015GenClipEofEng.zip/Regions_December_2015_Generalised_Clipped_Boundaries_in_England.shx                                        |
| %transferDirectory%objects/a0000000a.gdbtable                                                                                                                      |
| %transferDirectory%objects/Regions2015GenClipEofEng.zip/Regions_December_2015_Generalised_Clipped_Boundaries_in_England.dbf                                        |
| %transferDirectory%objects/England_ccg_2013.zip/england_ccg_2013.prj                                                                                               |
| %transferDirectory%objects/GBR_adm_shp.zip/GBR_adm2.dbf                                                                                                            |
| %transferDirectory%objects/GBR_adm2.zip/GBR_adm2.sbx                                                                                                               |
| %transferDirectory%objects/a00000001.TablesByName.atx                                                                                                              |
| %transferDirectory%objects/england_gor_2001.zip/england_gor_2001.shx                                                                                               |
| %transferDirectory%objects/GBR_adm1citation-ris.ris                                                                                                                |
| %transferDirectory%objects/England_nhscr_2013.zip/england_nhscr_2013.prj                                                                                           |
| %transferDirectory%objects/GBR_adm_shp.zip/license.txt                                                                                                             |
| %transferDirectory%objects/a00000007.CatRelTypesByUUID.atx                                                                                                         |
| %transferDirectory%objects/GBR_adm_shp.zip/GBR_adm1.prj                                                                                                            |
| %transferDirectory%objects/Regions.zip/TermsAndConditions.html                                                                                                     |
| %transferDirectory%objects/a00000003.gdbtable                                                                                                                      |
| %transferDirectory%objects/soils.zip                                                                                                                               |
| %transferDirectory%objects/england_ccg_2013.zip/england_ccg_2013.dbf                                                                                               |
| %transferDirectory%objects/GBR_adm_shp.zip/GBR_adm1.shp                                                                                                            |
| %transferDirectory%objects/CCG_BSC_Apr2015.KML                                                                                                                     |
| %transferDirectory%objects/GBR_adm1.zip/GBR_adm1.shx                                                                                                               |
| %transferDirectory%objects/england_gor_2001.zip/england_gor_2001.sbn                                                                                               |
| %transferDirectory%objects/gdb                                                                                                                                     |
| %transferDirectory%objects/soils.zip/england_nhsat_2013.shx                                                                                                        |
| %transferDirectory%objects/license.txt                                                                                                                             |
| %transferDirectory%objects/a00000007.gdbindexes                                                                                                                    |
| %transferDirectory%objects/Regions.zip/england_gor_2001.dbf                                                                                                        |
| %transferDirectory%objects/GBR_adm2.csv                                                                                                                            |
| %transferDirectory%objects/a00000006.gdbtable                                                                                                                      |
| %transferDirectory%objects/england_gor_2001.zip/england_gor_2001.shp                                                                                               |
| %transferDirectory%objects/GBR_adm0.csv                                                                                                                            |
| %transferDirectory%objects/GBR_adm_shp.zip/GBR_adm0.dbf                                                                                                            |
| %transferDirectory%objects/GBR_adm0.zip/GBR_adm0.sbx                                                                                                               |
| %transferDirectory%objects/GBR_adm_shp.zip/GBR_adm2.csv                                                                                                            |
| %transferDirectory%objects/GBR_adm_shp.zip/GBR_adm0.prj                                                                                                            |
| %transferDirectory%objects/a00000005.CatItemTypesByParentTypeID.atx                                                                                                |
| %transferDirectory%objects/Wales_ol_2001.zip/wales_ol_2001.prj                                                                                                     |
| %transferDirectory%objects/england_nhscr_2013.zip/england_nhscr_2013.dbf                                                                                           |
| %transferDirectory%objects/GBR_adm_shp.zip/GBR_adm0.cpg                                                                                                            |
| %transferDirectory%objects/a00000006.gdbindexes                                                                                                                    |
| %transferDirectory%objects/a00000006.FDO_UUID.atx                                                                                                                  |
| %transferDirectory%objects/england_nhscr_2013.zip/england_nhscr_2013.prj                                                                                           |
| %transferDirectory%objects/england_nhsat_2013.zip/england_nhsat_2013.prj                                                                                           |
| %transferDirectory%objects/GBR_adm2.zip/GBR_adm2.cpg                                                                                                               |
| %transferDirectory%objects/a00000004.FDO_UUID.atx                                                                                                                  |
| %transferDirectory%objects/wales_ol_2001.zip/wales_ol_2001.prj                                                                                                     |
| %transferDirectory%objects/GBR_adm2.zip/GBR_adm2.prj                                                                                                               |
| %transferDirectory%objects/GBR_adm2.zip/GBR_adm2.sbn                                                                                                               |
| %transferDirectory%objects/a00000006.CatRelsByType.atx                                                                                                             |
| %transferDirectory%objects/GBR_adm2.zip/GBR_adm2.dbf                                                                                                               |
| %transferDirectory%objects/Regions2015GenClipEofEng.zip                                                                                                            |
| %transferDirectory%objects/GBR_adm2citation-bib.bib                                                                                                                |
| %transferDirectory%objects/al_ta_on_shp_eng.zip                                                                                                                    |
| %transferDirectory%objects/a00000001.gdbtablx                                                                                                                      |
| %transferDirectory%objects/GBR_adm2.tab                                                                                                                            |
| %transferDirectory%objects/a00000002.gdbtablx                                                                                                                      |
| %transferDirectory%objects/Regions_December_2015_Generalised_Clipped_Boundaries_in_England.xml                                                                     |
| %transferDirectory%objects/soils.zip/england_nhsat_2013.dbf                                                                                                        |
| %transferDirectory%objects/GBR_adm0.zip                                                                                                                            |
| %transferDirectory%objects/a0000000a.gdbtablx                                                                                                                      |
| %transferDirectory%objects/GBR_adm_shp.zip/GBR_adm2.shp                                                                                                            |
| %transferDirectory%objects/Regions_December_2015_Generalised_Clipped_Boundaries_in_England.zip/Regions_December_2015_Generalised_Clipped_Boundaries_in_England.prj |
| %transferDirectory%objects/England_nhscr_2013.zip/england_nhscr_2013.dbf                                                                                           |
| %transferDirectory%objects/a00000007.CatRelTypesByForwardLabel.atx                                                                                                 |
| %transferDirectory%objects/a00000006.CatRelsByDestinationID.atx                                                                                                    |
| %transferDirectory%objects/england_nhsat_2013.zip/england_nhsat_2013.shp                                                                                           |
| %transferDirectory%objects/england_gor_2001.zip                                                                                                                    |
| %transferDirectory%objects/a00000007.gdbtablx                                                                                                                      |
| %transferDirectory%objects/GBR_adm0.zip/GBR_adm0.cpg                                                                                                               |
| %transferDirectory%objects/england_nhsat_2013.zip/england_nhsat_2013.sbx                                                                                           |
| %transferDirectory%objects/a00000006.CatRelsByOriginID.atx                                                                                                         |
| %transferDirectory%objects/Regions_December_2015_Generalised_Clipped_Boundaries_in_England.zip/Regions_December_2015_Generalised_Clipped_Boundaries_in_England.shp |
| %transferDirectory%objects/Regions_December_2015_Generalised_Clipped_Boundaries_in_England.zip/Regions_December_2015_Generalised_Clipped_Boundaries_in_England.shx |
| %transferDirectory%objects/Regions_December_2015_Generalised_Clipped_Boundaries_in_England.zip                                                                     |
| %transferDirectory%objects/England_ccg_2013.zip/england_ccg_2013.shx                                                                                               |
| %transferDirectory%objects/england_ccg_2013.zip/england_ccg_2013.shp                                                                                               |
| %transferDirectory%objects/GBR_adm_shp.zip/GBR_adm1.dbf                                                                                                            |
| %transferDirectory%objects/a00000005.gdbtablx                                                                                                                      |
| %transferDirectory%objects/Regions.zip/england_gor_2001.shp                                                                                                        |
| %transferDirectory%objects/wales_ol_2001.zip/wales_ol_2001.shp                                                                                                     |
| %transferDirectory%objects/GBR_adm_shp.zip/GBR_adm2.prj                                                                                                            |
| %transferDirectory%objects/GBR_adm0citation-ris.ris                                                                                                                |
| %transferDirectory%objects/GBR_adm0-ddi.xml                                                                                                                        |
| %transferDirectory%objects/a00000007.CatRelTypesByBackwardLabel.atx                                                                                                |
| %transferDirectory%objects/GBR_adm2citation-ris.ris                                                                                                                |
| %transferDirectory%objects/a00000004.spx                                                                                                                           |
| %transferDirectory%objects/GBR_adm0.zip/GBR_adm0.prj                                                                                                               |
| %transferDirectory%objects/GBR_adm_shp.zip/GBR_adm0.shp                                                                                                            |
| %transferDirectory%objects/GBR_adm0.zip/GBR_adm0.shx                                                                                                               |
| %transferDirectory%objects/GBR_adm1.tab                                                                                                                            |
| %transferDirectory%objects/GBR_adm1.csv                                                                                                                            |
| %transferDirectory%objects/wales_ol_2001.zip/wales_ol_2001.sbx                                                                                                     |
| %transferDirectory%objects/Wales_ol_2001.zip/wales_ol_2001.shx                                                                                                     |
| %transferDirectory%objects/GBR_adm2-ddi.xml                                                                                                                        |
| %transferDirectory%objects/GBR_adm_shp.zip/GBR_adm2.shx                                                                                                            |
| %transferDirectory%objects/soils.zip/TermsAndConditions.html                                                                                                       |
| %transferDirectory%objects/GBR_adm1.zip/GBR_adm1.sbx                                                                                                               |
| %transferDirectory%objects/england_nhsat_2013.zip/england_nhsat_2013.sbn                                                                                           |
| %transferDirectory%objects/england_nhsat_2013.zip/england_nhsat_2013.shx                                                                                           |
| %transferDirectory%objects/england_nhscr_2013.zip                                                                                                                  |
| %transferDirectory%objects/a00000004.gdbindexes                                                                                                                    |
| %transferDirectory%objects/Wales_ol_2001.zip/wales_ol_2001.dbf                                                                                                     |
| %transferDirectory%objects/GBR_adm0.zip/GBR_adm0.shp                                                                                                               |
| %transferDirectory%objects/a00000004.gdbtablx                                                                                                                      |
| %transferDirectory%objects/GBR_adm_shp.zip/GBR_adm1.csv                                                                                                            |
| %transferDirectory%objects/GBR_adm_shp.zip/GBR_adm0.shx                                                                                                            |
| %transferDirectory%objects/a00000005.gdbindexes                                                                                                                    |
| %transferDirectory%objects/GBR_adm_shp.zip/GBR_adm0.csv                                                                                                            |
| %transferDirectory%objects/GBR_adm0.zip/GBR_adm0.sbn                                                                                                               |
| %transferDirectory%objects/Regions.zip/england_gor_2001.prj                                                                                                        |
| %transferDirectory%objects/GBR_adm_shp.zip/GBR_adm1.shx                                                                                                            |
| %transferDirectory%objects/england_gor_2001.zip/england_gor_2001.prj                                                                                               |
| %transferDirectory%objects/england_gor_2001.zip/england_gor_2001.cpg                                                                                               |
| %transferDirectory%objects/england_gor_2001.zip/england_gor_2001.dbf                                                                                               |
| %transferDirectory%objects/GBR_adm1-ddi.xml                                                                                                                        |
| %transferDirectory%objects/GBR_adm2citation-endnote.xml                                                                                                            |
| %transferDirectory%objects/wales_ol_2001.zip/wales_ol_2001.dbf                                                                                                     |
| %transferDirectory%objects/GBR_adm0.tab                                                                                                                            |
| %transferDirectory%objects/a00000005.gdbtable                                                                                                                      |
| %transferDirectory%objects/england_nhscr_2013.zip/england_nhscr_2013.shp                                                                                           |
| %transferDirectory%objects/Regions_December_2015_Generalised_Clipped_Boundaries_in_England.zip/Regions_December_2015_Generalised_Clipped_Boundaries_in_England.sbn |
| %transferDirectory%objects/Wales_ol_2001.zip/TermsAndConditions.html                                                                                               |
| %transferDirectory%objects/a00000005.CatItemTypesByUUID.atx                                                                                                        |
| %transferDirectory%objects/GBR_adm0.zip/GBR_adm0.dbf                                                                                                               |
| %transferDirectory%objects/GBR_adm1citation-bib.bib                                                                                                                |
| %transferDirectory%objects/GBR_adm1.zip/GBR_adm1.sbn                                                                                                               |
| %transferDirectory%objects/GBR_adm1.zip/GBR_adm1.cpg                                                                                                               |
| %transferDirectory%objects/a00000007.CatRelTypesByOriginItemTypeID.atx                                                                                             |
| %transferDirectory%objects/a00000001.gdbindexes                                                                                                                    |
| %transferDirectory%objects/England_nhscr_2013.zip                                                                                                                  |
| %transferDirectory%objects/England_nhscr_2013.zip/england_nhscr_2013.shp                                                                                           |
| %transferDirectory%objects/CCG_BSC_Apr2015.lyr                                                                                                                     |
| %transferDirectory%objects/a00000007.gdbtable                                                                                                                      |
| %transferDirectory%objects/GBR_adm_shp.zip/GBR_adm2.cpg                                                                                                            |
| %transferDirectory%objects/england_nhsat_2013.zip                                                                                                                  |
| %transferDirectory%objects/Wales_ol_2001.zip/wales_ol_2001.shp                                                                                                     |
| %transferDirectory%objects/TermsAndConditions.html                                                                                                                 |
| %transferDirectory%objects/GBR_adm_shp.zip/GBR_adm1.cpg                                                                                                            |
| %transferDirectory%objects/Regions.zip/england_gor_2001.shx                                                                                                        |
| %transferDirectory%objects/a00000004.gdbtable                                                                                                                      |
| %transferDirectory%objects/GBR_adm1.zip/GBR_adm1.dbf                                                                                                               |
| %transferDirectory%objects/Regions_December_2015_Generalised_Clipped_Boundaries_in_England.zip/Regions_December_2015_Generalised_Clipped_Boundaries_in_England.sbx
```

**Comment by ross-spencer** [comment]
Hi @joel-simpson I think i have an enhancement to the existing PR to solve this issue, but I have spotted this one in the process unfortunately, we'll need to discuss over the next few days: https://github.com/archivematica/Issues/issues/116

**Comment by joel-simpson** [comment]
I have tested datasets with packages, both extracting them and not extracting them. Seems to be working fine! 
I have not attempted to leave packages in the AIP, due to archivematica/Issues#116. 
But as that is a separate issue I'm moving this to 'in progress'.

**Comment by ross-spencer** [comment]
For folks testing this card, the original issues were resolved, but some datasets still fail for other reasons. Other cards are being created for those as we test: e.g. https://github.com/archivematica/Issues/issues/211

**Comment by sallain** [comment]
This is minor, but sometime between Joel's screencap in the first comment on this thread and now, the microservice and job names have been title-cased - `Microservice: Parse External Files` and `Job: Determine Parse Dataverse METS XML`. We use sentence case for everything else.

Also, is the Job name grammatically correct?

**Comment by ablwr** [comment]
Testing this and it's fine but wondering about @sallain last comment?

**Comment by sallain** [comment]
@ross-spencer Were you the dev on this? Re: my previous comment about the microservice and job names.

**Comment by ablwr** [comment]
We could also open up a new issue for that and move this big one to verified?

**Comment by ross-spencer** [comment]
@sallain I was! Sorry, I didn't respond earlier.

I agree with @ablwr a new ticket for the naming convention issues is a good idea and we can move this to verified.
