### ISSUE TITLE
Problem: python-clamd fails to detect INSTREAM error from clamd

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica#779]
This is a sequel of #753. When we're using python-clamd to talk to clamd (new in AM17) and we're streaming the file (INSTREAM) and we hit the max filesize limit clamd returns an error and closes the connection - this behaviour is the expected as it's documented in the clamd docs.

However python-clamd raises an Exception under this situation. I think that python-clamd needs to be update to handle it gracefully.

```
In [18]: c.instream(open('/tmp/big-file'))
---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
<ipython-input-18-26788bd2b854> in <module>()
----> 1 c.instream(open('/tmp/big-file'))

/home/jesus/env-test-py/local/lib/python2.7/site-packages/clamd/__init__.pyc in instream(self, buff)
    188             while chunk:
    189                 size = struct.pack(b'!L', len(chunk))
--> 190                 self.clamd_socket.send(size + chunk)
    191                 chunk = buff.read(max_chunk_size)
    192

error: [Errno 104] Connection reset by peer
```

This is not a priority for AM17 because #772 mitigates the issue by not sending big files to clamd at all and use the local clamscan command-line tool instead.

This was never caught before because before using python-clamd we were using clamdscan (the official clamd cli client) which gracefully managed the situation mentioned before but it was still passing the file as clean even when it was a big file with viruses in it.

**Comment by sevein** [comment]
[xael/pyclamd](https://bitbucket.org/xael/pyclamd) seems to run into the same issue:

```
In [17]: print(cd.scan_stream(open('/tmp/big-file')))
---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
<ipython-input-17-061ef674d6b1> in <module>()
----> 1 print(cd.scan_stream(open('/tmp/big-file')))

/home/jesus/pyclamd.py in scan_stream(self, stream, chunk_size)
    552                 size = struct.pack('!L', len(chunk))
    553                 try:
--> 554                     self.clamd_socket.send(size)
    555                     self.clamd_socket.send(chunk)
    556                 except socket.error:

error: [Errno 104] Connection reset by peer
```

They catch the `socket.error` exception but it's just raised, there isn't error handling in place.

```python
    def scan_stream(self):

        # [Omitted for sake of simplicity...]

        if is_file_like:
            while True:
                chunk = stream.read(chunk_size)
                if not chunk:
                    break
                size = struct.pack('!L', len(chunk))
                try:
                    self.clamd_socket.send(size)
                    self.clamd_socket.send(chunk)
                except socket.error:
                    raise

            # Terminating stream
            self.clamd_socket.send(struct.pack('!L', 0))
        else:
            # bytearray
            for n in range(1 + int(len(stream)/chunk_size)):
                chunk = stream[n*chunk_size:(n+1)*chunk_size]
                size = struct.pack('!L', len(chunk))
                try:
                    self.clamd_socket.send(size)
                    self.clamd_socket.send(chunk)
                except socket.error:
                    raise
            else:
                # Terminating stream
                self.clamd_socket.send(struct.pack('!L', 0))
```

**Comment by ross-spencer** [comment]
See: https://wiki.jenkins.io/display/JENKINS/ClamAV+Plugin

**Comment by ross-spencer** [comment]
Ensure in catching/handling, that an appropriate event is made/not made. This essentially falls into category of `'no virus scan occurs so no event is made'`

**Comment by ross-spencer** [comment]
Further example trace:

```archivematicaClamscan.py: INFO      2017-12-07 19:32:48,962  archivematica.mcp.client.clamscan:scan_file:278:  Using scanner ClamAV (clamd) (ClamAV 0.99.2 - 24107/Thu Dec  7 02:16:40 2017)
archivematicaClamscan.py: ERROR     2017-12-07 19:32:50,422  archivematica.mcp.client.clamscan:scan:118:  Virus scanning failed: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/src/MCPClient/lib/clientScripts/archivematicaClamscan.py", line 115, in scan
    result = getattr(self, method_name)(path)
  File "/src/MCPClient/lib/clientScripts/archivematicaClamscan.py", line 144, in pass_by_value
    return self.client.instream(open(path))
  File "/usr/local/lib/python2.7/dist-packages/clamd/__init__.py", line 190, in instream
    self.clamd_socket.send(size + chunk)
error: [Errno 32] Broken pipe```

**Comment by sevein** [comment]
Notice though that it's a controlled exception that it's being logged as an `ERROR` and `exc_info=True` so the traceback is printed.

https://github.com/artefactual/archivematica/blob/0c748d9f448b8d18961fc8cb764c0149e56fd11b/src/MCPClient/lib/clientScripts/archivematicaClamscan.py#L113-L122
