### ISSUE TITLE
Submission Approval via REST API Fails After Idle Time.

### ISSUE THREAD

**Issue by dnarc** [artefactual/archivematica#788]
I've now seen this behaviour several times: I exclusively initiate transfers via the REST API but if an Archivematica instance called in this way is idle for some period (usually a few days), the 'Approve Submission' REST call no longer works, causing the transfer to fail. (Archivematica 1.6.1). Restarting archivematica-mcp-server fixes the issue.

Various logs show this:

ERROR     2017-11-06 17:24:37  archivematica.mcp.server.rpcserver:RPCServer:gearmanApproveJob:66:  Error approving job
Traceback (most recent call last):
  File "/usr/lib/archivematica/MCPServer/RPCServer.py", line 63, in gearmanApproveJob
    return cPickle.dumps(approveJob(jobUUID, chain, user_id))
  File "/usr/lib/archivematica/MCPServer/RPCServer.py", line 54, in approveJob
    choicesAvailableForUnits[jobUUID].proceedWithChoice(chain, user_id)
  File "/usr/lib/archivematica/MCPServer/utils.py", line 13, in wrapped
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django_mysqlpool/__init__.py", line 10, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/archivematica/MCPServer/linkTaskManagerChoice.py", line 143, in proceedWithChoice
    agent_id = UserProfile.objects.get(user_id=int(user_id)).agent_id
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 328, in get
    num = len(clone)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 144, in __len__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 226, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
OperationalError: (2006, 'MySQL server has gone away')

archivematica/dashboard/dashboard.debug.log:DEBUG     2017-11-06 17:24:22  archivematica.dashboard:models:create_user_agent:76:  Caught post_save signal from <class 'django.contrib.auth.models.User'> with
 instance <User: frdr>
archivematica/dashboard/dashboard.debug.log:DEBUG     2017-11-06 17:24:22  archivematica.dashboard:models:create_user_agent:84:  Agent: Archivematica user; Archivematica user pk: 1; username="frdr", first
_name="", last_name=""; created: False

archivematica/MCPServer/MCPServer.log:ERROR     2017-11-06 17:24:37  sqlalchemy.pool.QueuePool:pool:_finalize_fairy:696:  Exception during reset or similar
archivematica/MCPServer/MCPServer.log:ERROR     2017-11-06 17:24:37  archivematica.mcp.server:utils:wrapped:15:  Uncaught exception
archivematica/MCPServer/MCPServer.log:ERROR     2017-11-06 17:24:37  archivematica.mcp.server.rpcserver:RPCServer:gearmanApproveJob:66:  Error approving job

**Comment by jhsimpson** [comment]
I wonder if https://github.com/artefactual/archivematica/pull/762 will address this issue, @dnarc ?  From the stack trace and your description, it sounds like MCP Server is using up all its available database connections and new queries a few days later are not able to get a new connection.

Are you able to test with the 1.7.0 release candidate?

**Comment by dnarc** [comment]
Thanks, Justin et al. I will be able to try this next week.

**Comment by dnarc** [comment]
Are there any mitigations beyond testing with 1.7RC1? I am currently experimenting with setting the mysql wait_timeout to a very high value which should cause the db connections to never go stale but I'm worried there may be side effects from doing this.

**Comment by sevein** [comment]
Fixed in AM17. @dnarc let me know if you need more help with this.

**Comment by sevein** [comment]
The only issue I can think of with having very high `wait_timeout` values is that MySQL uses threads and they'll start to accumulate. Too many threads can be expensive and slow down your system.
