### ISSUE TITLE
Problem: can't download pointer file

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica#809]
I noticed yesterday running am.git (`6b358fe68c78bf5297598b2843fe877bdfb9103d`) that the `Store the AIP` job was failing silently (showing green status):

### STDOUT

```
Storage service created SIP: {u'error_message': u"[Errno 21] Is a directory: u'/var/archivematica/sharedDirectory/www/AIPsStore/0715/9594/6fcc/47d2/acad/4218/68e5/d553/Prueba3-07159594-6fcc-47d2-acad-421868e5d553'", u'traceback': u'Traceback (most recent call last):\n\n  File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 220, in wrapper\n    response = callback(request, *args, **kwargs)\n\n  File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 451, in dispatch_list\n    return self.dispatch(\'list\', request, **kwargs)\n\n  File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 483, in dispatch\n    response = method(request, **kwargs)\n\n  File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 1380, in post_list\n    updated_bundle = self.obj_create(bundle, **self.remove_api_resource_names(kwargs))\n\n  File "/src/storage_service/locations/api/resources.py", line 572, in obj_create\n    premis_agents=agents, aip_subtype=aip_subtype)\n\n  File "/src/storage_service/locations/models/package.py", line 606, in store_aip\n    aip_subtype=aip_subtype)\n\n  File "/src/storage_service/locations/models/package.py", line 749, in _store_aip_ensure_pointer_file\n    premis_agents=premis_agents, aip_subtype=aip_subtype)\n\n  File "/src/storage_service/locations/models/package.py", line 770, in _create_pointer_file_write_to_disk\n    self.fetch_local_path(), checksum_algorithm).hexdigest()\n\n  File "/src/storage_service/common/utils.py", line 285, in generate_checksum\n    with open(file_path, \'rb\') as f:\n\nIOError: [Errno 21] Is a directory: u\'/var/archivematica/sharedDirectory/www/AIPsStore/0715/9594/6fcc/47d2/acad/4218/68e5/d553/Prueba3-07159594-6fcc-47d2-acad-421868e5d553\'\n'}
```

### STDERR

```
storeAIP.py: INFO      2017-11-24 00:32:07,808  archivematica.common:create_file:278:  Creating file with {'current_path': 'Prueba3-07159594-6fcc-47d2-acad-421868e5d553', 'related_package_uuid': None, 'agents': [], 'current_location': '/api/v2/location/5757bfbb-3f58-4e87-8776-cc448f98f9c6/', 'size': 3864498, 'origin_path': u'currentlyProcessing/Prueba3-07159594-6fcc-47d2-acad-421868e5d553/Prueba3-07159594-6fcc-47d2-acad-421868e5d553/', 'origin_pipeline': u'/api/v2/pipeline/936a6afa-8564-4dae-b5ce-309b46363386/', 'uuid': '07159594-6fcc-47d2-acad-421868e5d553', 'package_type': 'AIP', 'origin_location': u'/api/v2/location/b8320e72-5d05-4567-bb9e-08d192055bab/', 'aip_subtype': 'Archival Information Package', 'events': []}
storeAIP.py: INFO      2017-11-24 00:32:08,241  archivematica.common:create_file:294:  Status code of create file/package request: 500
storeAIP.py: INFO      2017-11-24 00:32:08,242  archivematica.mcp.client.storeAIP:store_aip:171:  Storage service created SIP: {u'error_message': u"[Errno 21] Is a directory: u'/var/archivematica/sharedDirectory/www/AIPsStore/0715/9594/6fcc/47d2/acad/4218/68e5/d553/Prueba3-07159594-6fcc-47d2-acad-421868e5d553'", u'traceback': u'Traceback (most recent call last):\n\n  File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 220, in wrapper\n    response = callback(request, *args, **kwargs)\n\n  File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 451, in dispatch_list\n    return self.dispatch(\'list\', request, **kwargs)\n\n  File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 483, in dispatch\n    response = method(request, **kwargs)\n\n  File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 1380, in post_list\n    updated_bundle = self.obj_create(bundle, **self.remove_api_resource_names(kwargs))\n\n  File "/src/storage_service/locations/api/resources.py", line 572, in obj_create\n    premis_agents=agents, aip_subtype=aip_subtype)\n\n  File "/src/storage_service/locations/models/package.py", line 606, in store_aip\n    aip_subtype=aip_subtype)\n\n  File "/src/storage_service/locations/models/package.py", line 749, in _store_aip_ensure_pointer_file\n    premis_agents=premis_agents, aip_subtype=aip_subtype)\n\n  File "/src/storage_service/locations/models/package.py", line 770, in _create_pointer_file_write_to_disk\n    self.fetch_local_path(), checksum_algorithm).hexdigest()\n\n  File "/src/storage_service/common/utils.py", line 285, in generate_checksum\n    with open(file_path, \'rb\') as f:\n\nIOError: [Errno 21] Is a directory: u\'/var/archivematica/sharedDirectory/www/AIPsStore/0715/9594/6fcc/47d2/acad/4218/68e5/d553/Prueba3-07159594-6fcc-47d2-acad-421868e5d553\'\n'}
```

Somehow the SS breaks because `generate_checksum` is trying to run `open(file_path, 'rb')` where `file_path` seems to be a directory causing the `IOError:21` exception.

I think that as a result the pointer file is not being generated and I'm unable to download it.

**Comment by jrwdunham** [comment]
I think this is caused by the `or` in https://github.com/artefactual/archivematica-storage-service/blob/qa/0.x/storage_service/locations/models/package.py#L565 which should be an `and`.

**Comment by sevein** [comment]
This is likely solved but we need to confirm.

**Comment by currmie** [comment]
Hi @sevein - any specific scenario(s) you would like me to target for testing?

**Comment by sevein** [comment]
Not that I can remember. Thank you.

**Comment by currmie** [comment]
@sevein - I ran a couple of standard transfers with imported descriptive metadata on the following test servers: am17x.qa, centos17x.qa, and augustus.qa. Processing config kept the same on all 3 test environments. Resulting AIPs are stored. However, I cannot access the pointer file for the AIP on augustus.

lemur3_1_1 UUID: 21a49c77-8c28-475c-a64f-f36a47a36912
When I try to view pointer file, I see:
message:     "Storage service returned 404; check logs?"
success:      false

**Comment by sevein** [comment]
@currmie, @mamedin is taking a look. Thanks.

**Comment by mamedin** [comment]
@currmie, the default processing configuration on augustus was configured to not create compressed AIPs. I changed the default processing configuration to compress AIPs and I get the pointer file for the new transfers.
