### ISSUE TITLE
Unable to update storage server in Archivematica 1.8 after misentry

### ISSUE THREAD

**Issue by jpellman** [artefactual/archivematica#869]
On a CentOS 7 VM during the post-installation steps for Archivematica 1.8, I accidentally misentered the storage service URL in the dashboard.  This produced the following error in the web interface:

```
Storage server inaccessible. Please contact an administrator or update storage service URL below.
```

I attempted to update the storage service URL without luck.  The contents of /var/log/archivematica/dashboard/dashboard.log displayed a number of errors similar to the following:

```
HTTPError: 404 Client Error: NOT FOUND for url: http://localhost:8001/api/v2/pipeline/823c3af0-7940-46cb-8ec2-87a8759566fc/
ERROR     2017-12-05 18:39:15  archivematica.dashboard:views:transfer_source_locations:59:  Error retrieving source directories
Traceback (most recent call last):
  File "/usr/share/archivematica/dashboard/components/transfer/views.py", line 56, in transfer_source_locations
    return helpers.json_response(storage_service.get_location(purpose="TS"))
  File "/usr/lib/archivematica/archivematicaCommon/storageService.py", line 149, in get_location
    pipeline = _get_pipeline(get_setting('dashboard_uuid'))
  File "/usr/lib/archivematica/archivematicaCommon/storageService.py", line 123, in _get_pipeline
    response.raise_for_status()
  File "/usr/share/python/archivematica-dashboard/lib/python2.7/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: NOT FOUND for url: http://localhost:8001/api/v2/pipeline/823c3af0-7940-46cb-8ec2-87a8759566fc/
WARNING   2017-12-05 18:39:21  archivematica.common:storageService:_get_pipeline:122:  This Archivematica instance is not registered with the storage service or has been disabled.
WARNING   2017-12-05 18:39:21  archivematica.common:storageService:_get_pipeline:125:  Error fetching pipeline
Traceback (most recent call last):
  File "/usr/lib/archivematica/archivematicaCommon/storageService.py", line 123, in _get_pipeline
    response.raise_for_status()
  File "/usr/share/python/archivematica-dashboard/lib/python2.7/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: NOT FOUND for url: http://localhost:8001/api/v2/pipeline/823c3af0-7940-46cb-8ec2-87a8759566fc/
WARNING   2017-12-05 18:40:24  archivematica.common:storageService:_get_pipeline:122:  This Archivematica instance is not registered with the storage service or has been disabled.
WARNING   2017-12-05 18:40:24  archivematica.common:storageService:_get_pipeline:125:  Error fetching pipeline
Traceback (most recent call last):
  File "/usr/lib/archivematica/archivematicaCommon/storageService.py", line 123, in _get_pipeline
    response.raise_for_status()
  File "/usr/share/python/archivematica-dashboard/lib/python2.7/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: NOT FOUND for url: http://127.0.0.1:8001/api/v2/pipeline/823c3af0-7940-46cb-8ec2-87a8759566fc/
WARNING   2017-12-05 18:40:30  archivematica.common:storageService:_get_pipeline:122:  This Archivematica instance is not registered with the storage service or has been disabled.
WARNING   2017-12-05 18:40:30  archivematica.common:storageService:_get_pipeline:125:  Error fetching pipeline
Traceback (most recent call last):
  File "/usr/lib/archivematica/archivematicaCommon/storageService.py", line 123, in _get_pipeline
    response.raise_for_status()
  File "/usr/share/python/archivematica-dashboard/lib/python2.7/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: NOT FOUND for url: http://127.0.0.1:8001/api/v2/pipeline/823c3af0-7940-46cb-8ec2-87a8759566fc/
WARNING   2017-12-05 18:42:10  archivematica.common:storageService:_get_pipeline:122:  This Archivematica instance is not registered with the storage service or has been disabled.
WARNING   2017-12-05 18:42:10  archivematica.common:storageService:_get_pipeline:125:  Error fetching pipeline
Traceback (most recent call last):
  File "/usr/lib/archivematica/archivematicaCommon/storageService.py", line 123, in _get_pipeline
    response.raise_for_status()
  File "/usr/share/python/archivematica-dashboard/lib/python2.7/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: NOT FOUND for url: http://127.0.0.1:8001/api/v2/pipeline/823c3af0-7940-46cb-8ec2-87a8759566fc/
```

**Comment by jpellman** [comment]
Already separated out in #861
