### ISSUE TITLE
Problem: Virus Scanning is Failing with Diacritics

### ISSUE THREAD

**Issue by ross-spencer** [artefactual/archivematica#898]
This is related to a previous issue in the JISC RDSS Repository: https://github.com/JiscRDSS/rdss-archivematica/issues/57

But we're still seeing the message today, in qa/1.x:

```
archivematicaClamscan.py: WARNING   2018-01-24 14:29:07,928  archivematica.mcp.client.clamscan:get_scanner:278:  Unexpected antivirus scanner (CLAMAV_CLIENT_BACKEND): "clamddscanner"; using ClamdScanner.
archivematicaClamscan.py: INFO      2018-01-24 14:29:08,475  archivematica.mcp.client.clamscan:scan_file:335:  Using scanner ClamAV (clamd) (ClamAV 0.99.2 - 24249/Tue Jan 23 17:21:26 2018)
archivematicaClamscan.py: ERROR     2018-01-24 14:29:08,476  archivematica.mcp.client.clamscan:clamd_exception_handler:149:  Virus scanning failed: 'ascii' codec can't encode character u'\xe9' in position 115: ordinal not in range(128)
Traceback (most recent call last):
  File "/src/MCPClient/lib/clientScripts/archivematicaClamscan.py", line 116, in scan
    result = getattr(self, method_name)(path)
  File "/src/MCPClient/lib/clientScripts/archivematicaClamscan.py", line 172, in pass_by_value
    return self.client.instream(open(path))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 115: ordinal not in range(128)
archivematicaClamscan.py: INFO      2018-01-24 14:29:08,477  archivematica.mcp.client.clamscan:scan_file:348:  File /var/archivematica/sharedDirectory/currentlyProcessing/unicode-6ff2e0f3-3fba-4a9c-b0ec-aa7f44422a40/objects/4-23-PBé.pdf scanned!
archivematicaClamscan.py: INFO      2018-01-24 14:29:08,480  archivematica.mcp.client.clamscan:record_event:232:  Recording new event for file bdc5d050-0eb6-4325-ac24-b60224eee9d4 (outcome: Fail)
```
Example filename causing the issue: `4-23-PBé.pdf`

The first changes for this issue were part of commit: https://github.com/artefactual/archivematica/pull/743/commits/8d0f49510670bcacc81c0ad88cd7ab559ba917e6

The output from the script for AM running that commit is as follows:

```
Traceback (most recent call last):
  File "/src/MCPClient/lib/clientScripts/archivematicaClamscan.py", line 119, in <module>
    sys.exit(main(fileUUID, target, date))
  File "/src/MCPClient/lib/clientScripts/archivematicaClamscan.py", line 95, in main
    result = client.instream(open(target))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 109: ordinal not in range(128)
```
The script for virus scanning failing at this point in the transfer causes the transfer to fail which is undesirable behaviour noted here: https://github.com/artefactual/archivematica/issues/875

### Update 2018-01-24: Workaround:

Set the following ENVVAR to False:

```CLAMAV_PASS_BY_REFERENCE = True``` <-- Updated 1 Feb 2018

**Comment by ross-spencer** [comment]
If we switch between the original we see the following errors depending on whether we elect to stream, or pass by reference:

### stream with cmd_line_arg_to_unicode() in place

```
archivematicaClamscan.py: WARNING   2018-01-25 00:40:58,792  archivematica.mcp.client.clamscan:get_scanner:282:  Unexpected antivirus scanner (CLAMAV_CLIENT_BACKEND): "clamddscanner"; using ClamdScanner.
archivematicaClamscan.py: INFO      2018-01-25 00:40:58,795  archivematica.mcp.client.clamscan:scan_file:339:  Using scanner ClamAV (clamd) (ClamAV 0.99.2 - 24207/Tue Jan  9 21:18:11 2018)
archivematicaClamscan.py: INFO      2018-01-25 00:40:58,798  archivematica.mcp.client.clamscan:pass_by_value:175:  Passing file to clamd by value: stream.
archivematicaClamscan.py: ERROR     2018-01-25 00:40:58,799  archivematica.mcp.client.clamscan:clamd_exception_handler:151:  Virus scanning failed: 'ascii' codec can't encode character u'\xe9' in position 119: ordinal not in range(128)
Traceback (most recent call last):
  File "/src/MCPClient/lib/clientScripts/archivematicaClamscan.py", line 118, in scan
    result = getattr(self, method_name)(path)
  File "/src/MCPClient/lib/clientScripts/archivematicaClamscan.py", line 176, in pass_by_value
    return self.client.instream(open(path))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 119: ordinal not in range(128)
archivematicaClamscan.py: INFO      2018-01-25 00:40:58,800  archivematica.mcp.client.clamscan:scan_file:352:  File /var/archivematica/sharedDirectory/currentlyProcessing/two-f8cbc200-d62e-4bc0-9cb4-56c94fa39b62/objects/Boreau de Roincé 2013.txt scanned!
archivematicaClamscan.py: INFO      2018-01-25 00:40:58,806  archivematica.mcp.client.clamscan:record_event:236:  Recording new event for file 6154fb68-9a23-46f4-8290-d96cbc721b42 (outcome: Fail)
```
### reference with no cmd_line_arg_to_unicode()

```
archivematicaClamscan.py: WARNING   2018-01-25 00:44:34,037  archivematica.mcp.client.clamscan:get_scanner:282:  Unexpected antivirus scanner (CLAMAV_CLIENT_BACKEND): "clamddscanner"; using ClamdScanner.
archivematicaClamscan.py: INFO      2018-01-25 00:44:34,043  archivematica.mcp.client.clamscan:scan_file:339:  Using scanner ClamAV (clamd) (ClamAV 0.99.2 - 24207/Tue Jan  9 21:18:11 2018)
archivematicaClamscan.py: INFO      2018-01-25 00:44:34,044  archivematica.mcp.client.clamscan:pass_by_reference:171:  Passing file to clamd by reference.
archivematicaClamscan.py: ERROR     2018-01-25 00:44:34,050  archivematica.mcp.client.clamscan:clamd_exception_handler:151:  Virus scanning failed: 'ascii' codec can't decode byte 0xc3 in position 119: ordinal not in range(128)
Traceback (most recent call last):
  File "/src/MCPClient/lib/clientScripts/archivematicaClamscan.py", line 118, in scan
    result = getattr(self, method_name)(path)
  File "/src/MCPClient/lib/clientScripts/archivematicaClamscan.py", line 172, in pass_by_reference
    return self.client.scan(path)
  File "/usr/local/lib/python2.7/dist-packages/clamd/__init__.py", line 114, in scan
    return self._file_system_scan('SCAN', file)
  File "/usr/local/lib/python2.7/dist-packages/clamd/__init__.py", line 154, in _file_system_scan
    self._send_command(command, file)
  File "/usr/local/lib/python2.7/dist-packages/clamd/__init__.py", line 229, in _send_command
    concat_args = ' ' + ' '.join(args)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 119: ordinal not in range(128)
archivematicaClamscan.py: INFO      2018-01-25 00:44:34,058  archivematica.mcp.client.clamscan:scan_file:352:  File /var/archivematica/sharedDirectory/currentlyProcessing/ref-afe0ca68-4a7b-4efa-9c7e-d2892c1c4102/objects/Boreau de Roincé 2013.txt scanned!
archivematicaClamscan.py: INFO      2018-01-25 00:44:34,059  archivematica.mcp.client.clamscan:record_event:236:  Recording new event for file 7a808822-a86c-4bc2-8ecd-c46dde39dcb4 (outcome: Fail)
```

**Comment by ross-spencer** [comment]
Using 1.0.2 of this lib: https://github.com/graingert/python-clamd/blob/5c5e33b2dfd0499470e15abeb83efb6531ef9ab7/src/clamd/__init__.py

**Comment by ross-spencer** [comment]
Docker archivematica-mcp-client locale:

```
ross-spencer@artefactual:~/git/artefactual-labs/am/compose:$ sudo docker exec -it 7e7e1b23f89b bash
archivematica@7e7e1b23f89b:/$ locale
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```

**Comment by ross-spencer** [comment]
We can say that the issue is caused by our assumption that the encoding of the system running AM should be `en_US.UTF-8` is incorrect. Especially across an increasingly distributed system.

This value is set early on in the `executeOrRunSubProcess` script if `LANG` is not specified by the OS: 
https://github.com/artefactual/archivematica/blob/0c748d9f448b8d18961fc8cb764c0149e56fd11b/src/archivematicaCommon/lib/executeOrRunSubProcess.py#L65

https://github.com/artefactual/archivematica/blob/0c748d9f448b8d18961fc8cb764c0149e56fd11b/src/archivematicaCommon/lib/executeOrRunSubProcess.py#L66 

If we put additional logging into the `MCPClient`, and compare it to the information above about encoding inside the container, we can see the problem develop:

```
archivematica-mcp-client_1       | archivematicaClient.py: INFO      2018-01-30 00:00:19,754  archivematica.mcp.client.executeOrRunSubProcess:launchSubProcess:71:  XLOCALE: Encoding created by AM in envars: en_US.UTF-8
archivematica-mcp-client_1       | archivematicaClient.py: INFO      2018-01-30 00:00:19,755  archivematica.mcp.client.executeOrRunSubProcess:launchSubProcess:72:  XLOCALE: default in container when created: (None, None)
archivematica-mcp-client_1       | archivematicaClamscan.py: INFO      2018-01-30 00:00:19,309  archivematica.mcp.client.archivematicaFunctions:get_locale_encoding:109:  XLOCALE: get default returned from envars: UTF-8
archivematica-mcp-client_1       | archivematicaClamscan.py: INFO      2018-01-30 00:00:19,349  archivematica.mcp.client.clamscan:pass_by_value:177:  XLOCALE clamscan running default Python open() <- system's encoding to send as stream.
archivematica-mcp-client_1       | archivematicaClamscan.py: INFO      2018-01-30 00:00:19,350  archivematica.mcp.client.clamscan:pass_by_value:178:  XLOCALE clamscan getdefaultlocale(): ('en_US', 'UTF-8')
archivematica-mcp-client_1       | archivematicaClamscan.py: INFO      2018-01-30 00:00:19,350  archivematica.mcp.client.clamscan:pass_by_value:179:  XLOCALE clamscan getlocale(): (None, None)
```
Running the locale command inside the `MCPClient` Container from `executeOrRunSubProcess` returns `(None, None)`

And running the locale command inside the `MCPClient` Container from the `archivematicaClamscan` script returns `('en_US', 'UTF-8')`

Python's `open()` command I believe to be running the default system locale, for which we find:

```
ross-spencer@artefactual:~/git/artefactual-labs/am/compose:$ sudo docker exec -it 7e7e1b23f89b bash
archivematica@7e7e1b23f89b:/$ locale
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```

If we set the locale in the container using:

```
# Set the locale
RUN locale-gen en_US.UTF-8  
ENV LANG en_US.UTF-8  
ENV LANGUAGE en_US:en  
ENV LC_ALL en_US.UTF-8
```

The transfer passes through as expected, the log as follows:

```
archivematica-mcp-client_1       | archivematicaClamscan.py: INFO      2018-01-30 01:59:45,240  archivematica.mcp.client.archivematicaFunctions:get_locale_encoding:109:  XLOCALE: get default returned from envars: UTF-8
archivematica-mcp-client_1       | archivematicaClamscan.py: INFO      2018-01-30 01:59:45,261  archivematica.mcp.client.clamscan:pass_by_value:177:  XLOCALE clamscan running default Python open() <- system's encoding to send as stream.
archivematica-mcp-client_1       | archivematicaClamscan.py: INFO      2018-01-30 01:59:45,261  archivematica.mcp.client.clamscan:pass_by_value:178:  XLOCALE clamscan getdefaultlocale(): ('en_US', 'UTF-8')
archivematica-mcp-client_1       | archivematicaClamscan.py: INFO      2018-01-30 01:59:45,261  archivematica.mcp.client.clamscan:pass_by_value:179:  XLOCALE clamscan getlocale(): (None, None)
```

**Note** the instruction missing: ` XLOCALE: Encoding created by AM in envars: en_US.UTF-8`

In terms of solutions, at the very least, setting the locale in each of the AM containers will be useful. In the long-run an alternative may be required.

**Comment by ross-spencer** [comment]
@jhsimpson @sevein @jrwdunham See above for comments that would be good to get an opinion on. :+1:

**Comment by ross-spencer** [comment]
**N.B.** We're using an Ubuntu image for the MCP Client, this returns the error:

```
Package locales-all is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'locales-all' has no installation candidate
```

Whereas locales-all is required for the other Debian messages we're running, e.g. from the dashboard:

```
Package locales-all is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'locales-all' has no installation candidate
```
