### ISSUE TITLE
Problem: Cannot rebuild transfer backlog when location is encrypted

### ISSUE THREAD

**Issue by mamedin** [artefactual/archivematica#916]
The new `rebuild_transfer_backlog` command fails with an encrypted transfer backlog.

```
(archivematica-dashboard) [archivematica@sfu-issue-10662 dashboard]$ ./manage.py rebuild_transfer_backlog --transfer-backlog-dir /var/archivematica/testEncryption/backlog
WARNING: This script will delete your current Elasticsearch transfer data, rebuilding it using files.
Are you sure you want to continue?

Type "yes" to continue, or "no" to cancel:  yes
Rebuilding "transfers" index from /var/archivematica/testEncryption/backlog/originals.
INFO      2018-02-07 19:51:29  elasticsearch:base:log_request_success:63:  PUT http://127.0.0.1:9200/aips [status:400 request:0.092s]
No handlers could be found for logger "elasticsearch.trace"
INFO      2018-02-07 19:51:29  elasticsearch:base:log_request_success:63:  GET http://127.0.0.1:9200/aips/_mapping/aipfile [status:200 request:0.012s]
INFO      2018-02-07 19:51:29  elasticsearch:base:log_request_success:63:  PUT http://127.0.0.1:9200/transfers [status:400 request:0.004s]
INFO      2018-02-07 19:51:29  elasticsearch:base:log_request_success:63:  GET http://127.0.0.1:9200/transfers/_mapping/transferfile [status:200 request:0.013s]
INFO      2018-02-07 19:51:29  elasticsearch:base:log_request_success:63:  GET http://127.0.0.1:9200/ [status:200 request:0.007s]
Connected to Elasticsearch node Kimura (v1.7.6).
Deleting all transfers in the "transfers" index...
INFO      2018-02-07 19:51:33  elasticsearch:base:log_request_success:63:  DELETE http://127.0.0.1:9200/transfers [status:200 request:0.062s]
Creating index...
INFO      2018-02-07 19:51:33  elasticsearch:base:log_request_success:63:  PUT http://127.0.0.1:9200/transfers [status:200 request:0.204s]
INFO      2018-02-07 19:51:33  archivematica.common:elasticSearchFunctions:set_up_mapping_transfer_index:373:  Creating transfer file mapping...
INFO      2018-02-07 19:51:33  elasticsearch:base:log_request_success:63:  PUT http://127.0.0.1:9200/transfers/_mapping/transferfile [status:200 request:0.046s]
INFO      2018-02-07 19:51:33  archivematica.common:elasticSearchFunctions:set_up_mapping_transfer_index:377:  Transfer file mapping created.
INFO      2018-02-07 19:51:33  archivematica.common:elasticSearchFunctions:set_up_mapping_transfer_index:388:  Creating transfer mapping...
INFO      2018-02-07 19:51:33  elasticsearch:base:log_request_success:63:  PUT http://127.0.0.1:9200/transfers/_mapping/transfer [status:200 request:0.069s]
INFO      2018-02-07 19:51:33  archivematica.common:elasticSearchFunctions:set_up_mapping_transfer_index:392:  Transfer mapping created.
INFO      2018-02-07 19:51:33  elasticsearch:base:log_request_success:63:  PUT http://127.0.0.1:9200/transfers [status:400 request:0.002s]
INFO      2018-02-07 19:51:33  elasticsearch:base:log_request_success:63:  GET http://127.0.0.1:9200/transfers/_mapping/transferfile [status:200 request:0.002s]
Indexing 9909deb7-abba-41b6-9df3-e52ac99d509b (sr-backlog1-9909deb7-abba-41b6-9df3-e52ac99d509b)
WARNING   2018-02-07 19:51:33  archivematica.common:elasticSearchFunctions:index_files:494:  Directory does not exist: /var/archivematica/testEncryption/backlog/originals/sr-backlog1-9909deb7-abba-41b6-9df3-e52ac99d509b/
Directory does not exist: /var/archivematica/testEncryption/backlog/originals/sr-backlog1-9909deb7-abba-41b6-9df3-e52ac99d509b/
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/share/python/archivematica-dashboard/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/share/python/archivematica-dashboard/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/share/python/archivematica-dashboard/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/share/python/archivematica-dashboard/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/opt/archivematica/archivematica/src/dashboard/src/main/management/commands/rebuild_transfer_backlog.py", line 76, in handle
    self.populate_index(es_client, transfer_backlog_dir)
  File "/opt/archivematica/archivematica/src/dashboard/src/main/management/commands/rebuild_transfer_backlog.py", line 128, in populate_index
    storageService.reindex_file(transfer_uuid)
  File "/usr/lib/archivematica/archivematicaCommon/storageService.py", line 454, in reindex_file
    response.raise_for_status()
  File "/usr/share/python/archivematica-dashboard/lib/python2.7/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://sfu-issue-10662.archivematica.org:8000/api/v2/file/9909deb7-abba-41b6-9df3-e52ac99d509b/reindex/
```

`` /var/archivematica/testEncryption/backlog/originals/sr-backlog1-9909deb7-abba-41b6-9df3-e52ac99d509b/`` is a GPG file:
``` 
(archivematica-dashboard) [archivematica@sfu-issue-10662 dashboard]$ file /var/archivematica/testEncryption/backlog/originals/sr-backlog1-9909deb7-abba-41b6-9df3-e52ac99d509b
/var/archivematica/testEncryption/backlog/originals/sr-backlog1-9909deb7-abba-41b6-9df3-e52ac99d509b: GPG encrypted data
```

**Comment by sevein** [comment]
@jrwdunham how should this be fixed?

**Comment by sevein** [comment]
Joel explained me that we would need to rebuild this task to make it work with the new encrypted spaces in SS.

**Comment by jrwdunham** [comment]
More than that, we would potentially need to modify the SS to provide a "decrypt" endpoint so that the command/AM could request a decryption. Maybe this could be done by requesting a move of the encrypted transfer in Backlog to another location...
