### ISSUE TITLE
Problem: migration 0033_store_transfer_file_modification_dates failed

### ISSUE THREAD

**Issue by scollazo** [artefactual/archivematica#959]
This might be a corner case, or caused by a deployment problem in the past.

This happened installing 1.7 migrations, in an AM 1.6.0 install using ansible on trusty, that was updated to 1.6.1,  and has been dist-upgraded to xenial, before deploying AM 1.7 using the ansible playbooks.

MySQL version is mysql-server-core-5.7

<pre>
root@test-161ubuntutrusty-updated-from-16withtransfers:/usr/share/archivematica/dashboard# /usr/share/python/archivematica-dashboard/bin/python manage.py migrate
Operations to perform:
  Synchronize unmigrated apps: django_forms_bootstrap, staticfiles, messages, webdesign, accounts, installer, mcp
  Apply all migrations: sessions, administration, tastypie, auth, contenttypes, fpr, longerusername, main
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying main.0031_job_currentstep_choices... OK
  Applying main.0032_dashboardsetting_scope... OK
  Applying administration.0007_delete_unused_models... OK
  Applying fpr.0011_mediaconch_validation... OK
  Applying fpr.0012_mediaconch_policy_checks... OK
  Applying fpr.0013_normalization_rules_mov... OK
  Applying fpr.0014_fix_fits_command... OK
  Applying fpr.0015_pronom_92...Installed 164 object(s) from 1 fixture(s)
 OK
  Applying fpr.0016_update_idtools... OK
  Applying fpr.0017_ocr_unique_names... OK
  Applying fpr.0018_slug_unique... OK
  Applying longerusername.0001_initial... OK
  Applying longerusername.0002_add_username_error_message... OK
  Applying main.0033_store_transfer_file_modification_dates...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/migrations/operations/fields.py", line 62, in database_forwards
    field,
  File "/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/backends/mysql/schema.py", line 43, in add_field
    super(DatabaseSchemaEditor, self).add_field(model, field)
  File "/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 398, in add_field
    self.execute(sql, params)
  File "/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 226, in execute
    self.errorhandler(self, exc, value)
  File "/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
django.db.utils.OperationalError: (1292, "Incorrect datetime value: '0000-00-00 00:00:00' for column 'modificationtime' at row 1")
<pre>

**Comment by mamedin** [comment]
Same problem here on ubuntu 16 after upgrading (from deb packages) from AM 1.6.1 to AM 1.7.

```
Running migrations:
  Rendering model states... DONE
  Applying main.0031_job_currentstep_choices... OK
  Applying main.0032_dashboardsetting_scope... OK
  Applying administration.0007_delete_unused_models... OK
  Applying fpr.0011_mediaconch_validation... OK
  Applying fpr.0012_mediaconch_policy_checks... OK
  Applying fpr.0013_normalization_rules_mov... OK
  Applying fpr.0014_fix_fits_command... OK
  Applying fpr.0015_pronom_92...Installed 164 object(s) from 1 fixture(s)
 OK
  Applying fpr.0016_update_idtools... OK
  Applying fpr.0017_ocr_unique_names... OK
  Applying fpr.0018_slug_unique... OK
  Applying longerusername.0001_initial... OK
  Applying longerusername.0002_add_username_error_message... OK
  Applying main.0033_store_transfer_file_modification_dates...Traceback (most recent call last):
  File "/usr/share/archivematica/dashboard/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/operations/fields.py", line 62, in database_forwards
    field,
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/schema.py", line 43, in add_field
    super(DatabaseSchemaEditor, self).add_field(model, field)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 398, in add_field
    self.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 226, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
django.db.utils.OperationalError: (1292, "Incorrect datetime value: '0000-00-00 00:00:00' for column 'modificationtime' at row 1")
```

**Comment by sevein** [comment]
@scollazo this is ready to be QA'ed.
