### ISSUE TITLE
Problem: unable to start transfer in centos

### ISSUE THREAD

**Issue by scollazo** [artefactual/archivematica#969]
Tested on centos7 using rpms

<pre>
INFO      2018-03-09 09:06:28  locations.models.space:space:browse:239:  path: /home
INFO      2018-03-09 09:06:37  locations.models.space:space:move_rsync:463:  Moving from /home/test/. to /var/archivematica/sharedDirectory/tmp/tmpc__abU/test/.
INFO      2018-03-09 09:06:37  locations.models.space:space:move_rsync:493:  rsync command: ['rsync', '-t', '-O', '--protect-args', '-vv', '--chmod=Fug+rw,o-rwx,Dug+rwx,o-rwx', '-r', '/home/test/.', '/var/archivematica/sharedDirectory/tmp/tmpc__abU/test/.']
ERROR     2018-03-09 09:06:41  django.request.tastypie:resources:_handle_500:301:  Internal Server Error: /api/v2/async/2/
Traceback (most recent call last):
  File "/usr/share/python/archivematica-storage-service/lib/python2.7/site-packages/tastypie/resources.py", line 220, in wrapper
    response = callback(request, *args, **kwargs)
  File "/usr/share/python/archivematica-storage-service/lib/python2.7/site-packages/tastypie/resources.py", line 460, in dispatch_detail
    return self.dispatch('detail', request, **kwargs)
  File "/usr/share/python/archivematica-storage-service/lib/python2.7/site-packages/tastypie/resources.py", line 483, in dispatch
    response = method(request, **kwargs)
  File "/usr/share/python/archivematica-storage-service/lib/python2.7/site-packages/tastypie/resources.py", line 1362, in get_detail
    bundle = self.full_dehydrate(bundle)
  File "/usr/share/python/archivematica-storage-service/lib/python2.7/site-packages/tastypie/resources.py", line 893, in full_dehydrate
    bundle = self.dehydrate(bundle)
  File "/usr/lib/archivematica/storage-service/locations/api/resources.py", line 1314, in dehydrate
    bundle.data['result'] = bundle.obj.result
  File "/usr/lib/archivematica/storage-service/locations/models/async.py", line 36, in result
    return cPickle.loads(self._result)
TypeError: must be string, not buffer
</pre>

Package versions:
<pre>
archivematica-storage-service-0.11.0-~rc.6_2_g73580d8.x86_64
archivematica-dashboard-1.7.0-~rc.3_3_ga91c8f1.x86_64
archivematica-mcp-server-1.7.0-~rc.3_3_ga91c8f1.x86_64
archivematica-common-1.7.0-~rc.3_3_ga91c8f1.x86_64
archivematica-mcp-client-1.7.0-~rc.3_3_ga91c8f1.x86_64
</pre>

This may be related to https://github.com/artefactual/archivematica/issues/961

**Comment by sevein** [comment]
@scollazo is your SS 0.11 package using stable/0.11.x or qa/0.x? From what I can see in the traceback it looks like it's the latter.

**Comment by scollazo** [comment]
There was an issue with rpm packages using the wrong branch, it has been fixed in https://github.com/artefactual-labs/am-packbuild/commit/05cf452037ad43ce57f53200d25a4186f46a28e7
