### ISSUE TITLE
Problem: Cannot rebuild transfer-backlog after upgrade

### ISSUE THREAD

**Issue by mamedin** [artefactual/archivematica#976]
After upgrading AM from 1.6.x to 1.7.x I cannot rebuild the transfer index with `manage.py rebuild_transfer_backlog`. I tried with Ubuntu 14 and CentOS 7, both installed from packages. It happens when the system has old data on the backlog or transfers. The index is created without problems in a clean system.

Ubuntu 14 error message:
```
(archivematica-dashboard) archivematica@santi-update-1:/usr/share/archivematica/dashboard$ ./manage.py rebuild_transfer_backlog --traceback --transfer-backlog-dir /var/archivematica/sharedDirectory/www/AIPsStore/transferBacklog
WARNING: This script will delete your current Elasticsearch transfer data, rebuilding it using files.
Are you sure you want to continue?

Type "yes" to continue, or "no" to cancel:  YES
Rebuilding "transfers" index from /var/archivematica/sharedDirectory/www/AIPsStore/transferBacklog/originals.
No handlers could be found for logger "elasticsearch.trace"
Connected to Elasticsearch node Isaiah Bradley (v1.7.6).
Deleting all transfers in the "transfers" index...
Creating index...
Indexing 8fd204cc-9624-4b7e-8db4-07159e840c52 (kk-8fd204cc-9624-4b7e-8db4-07159e840c52)
Skipping indexing kk-8fd204cc-9624-4b7e-8db4-07159e840c52/processingMCP.xml
Indexing kk-8fd204cc-9624-4b7e-8db4-07159e840c52/metadata/submissionDocumentation/METS.xml (UUID: )
Indexing kk-8fd204cc-9624-4b7e-8db4-07159e840c52/logs/filenameCleanup.log (UUID: )
Indexing kk-8fd204cc-9624-4b7e-8db4-07159e840c52/logs/fileFormatIdentification.log (UUID: )
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/share/archivematica/dashboard/main/management/commands/rebuild_transfer_backlog.py", line 76, in handle
    self.populate_index(es_client, transfer_backlog_dir)
  File "/usr/share/archivematica/dashboard/main/management/commands/rebuild_transfer_backlog.py", line 127, in populate_index
    transfer_uuid)
  File "/usr/share/archivematica/dashboard/main/management/commands/rebuild_transfer_backlog.py", line 137, in index_files
    status='backlog')
  File "/usr/lib/archivematica/archivematicaCommon/elasticSearchFunctions.py", line 521, in index_files
    status=status
  File "/usr/lib/archivematica/archivematicaCommon/elasticSearchFunctions.py", line 788, in index_transfer_files
    modification_date = f.modificationtime.strftime('%Y-%m-%d')
AttributeError: 'NoneType' object has no attribute 'strftime'
```

CentoS 7 error messages:
```
[root@mamedin-1 log]# sudo su - archivematica
[archivematica@mamedin-1 ~]$ source /usr/share/python/archivematica-dashboard/bin/activate
(archivematica-dashboard)[archivematica@mamedin-1 ~]$ export $(grep -v ^# /etc/sysconfig/archivematica-dashboard)
(archivematica-dashboard)[archivematica@mamedin-1 ~]$ cd /usr/share/archivematica/dashboard
(archivematica-dashboard)[archivematica@mamedin-1 dashboard]$ ./manage.py rebuild_transfer_backlog --transfer-backlog-dir  /var/archivematica/sharedDirectory/www/AIPsStore/transferBacklog
WARNING: This script will delete your current Elasticsearch transfer data, rebuilding it using files.
Are you sure you want to continue?

Type "yes" to continue, or "no" to cancel:  yes
Rebuilding "transfers" index from /var/archivematica/sharedDirectory/www/AIPsStore/transferBacklog/originals.
No handlers could be found for logger "elasticsearch.trace"
Connected to Elasticsearch node Chan Luichow (v1.7.6).
Deleting all transfers in the "transfers" index...
Creating index...
Indexing 4f9b6ed1-0af4-4800-b49a-dc9ca0df0432 (tester-4f9b6ed1-0af4-4800-b49a-dc9ca0df0432)
Indexing tester-4f9b6ed1-0af4-4800-b49a-dc9ca0df0432/metadata/submissionDocumentation/[datavibe-l]_FW__job_vacancy.rtf (UUID: )
Indexing tester-4f9b6ed1-0af4-4800-b49a-dc9ca0df0432/metadata/submissionDocumentation/METS.xml (UUID: )
Indexing tester-4f9b6ed1-0af4-4800-b49a-dc9ca0df0432/metadata/metadata.csv (UUID: )
Indexing tester-4f9b6ed1-0af4-4800-b49a-dc9ca0df0432/objects/Landing_zone.jpg (UUID: )
Indexing tester-4f9b6ed1-0af4-4800-b49a-dc9ca0df0432/objects/MARBLES.TGA (UUID: )
Indexing tester-4f9b6ed1-0af4-4800-b49a-dc9ca0df0432/logs/fileFormatIdentification.log (UUID: )
Indexing tester-4f9b6ed1-0af4-4800-b49a-dc9ca0df0432/logs/filenameCleanup.log (UUID: )
Skipping indexing tester-4f9b6ed1-0af4-4800-b49a-dc9ca0df0432/processingMCP.xml
transferfile UUID: 4f9b6ed1-0af4-4800-b49a-dc9ca0df0432
Files indexed: 7
Indexing 4a7ff692-775d-4f34-9aad-39e5b22dab1c (tt-4a7ff692-775d-4f34-9aad-39e5b22dab1c)
Indexing /var/archivematica/sharedDirectory/www/AIPsStore/transferBacklog/originals/tester-4f9b6ed1-0af4-4800-b49a-dc9ca0df0432/metadata/submissionDocumentation/[datavibe-l]_FW__job_vacancy.rtf (UUID: )
Indexing /var/archivematica/sharedDirectory/www/AIPsStore/transferBacklog/originals/tester-4f9b6ed1-0af4-4800-b49a-dc9ca0df0432/metadata/submissionDocumentation/METS.xml (UUID: )
Indexing /var/archivematica/sharedDirectory/www/AIPsStore/transferBacklog/originals/tester-4f9b6ed1-0af4-4800-b49a-dc9ca0df0432/metadata/metadata.csv (UUID: )
Indexing /var/archivematica/sharedDirectory/www/AIPsStore/transferBacklog/originals/tester-4f9b6ed1-0af4-4800-b49a-dc9ca0df0432/objects/Landing_zone.jpg (UUID: )
Indexing /var/archivematica/sharedDirectory/www/AIPsStore/transferBacklog/originals/tester-4f9b6ed1-0af4-4800-b49a-dc9ca0df0432/objects/MARBLES.TGA (UUID: )
Indexing /var/archivematica/sharedDirectory/www/AIPsStore/transferBacklog/originals/tester-4f9b6ed1-0af4-4800-b49a-dc9ca0df0432/logs/fileFormatIdentification.log (UUID: )
Indexing /var/archivematica/sharedDirectory/www/AIPsStore/transferBacklog/originals/tester-4f9b6ed1-0af4-4800-b49a-dc9ca0df0432/logs/filenameCleanup.log (UUID: )
Skipping indexing /var/archivematica/sharedDirectory/www/AIPsStore/transferBacklog/originals/tester-4f9b6ed1-0af4-4800-b49a-dc9ca0df0432/processingMCP.xml
Indexing tt-4a7ff692-775d-4f34-9aad-39e5b22dab1c/metadata/submissionDocumentation/METS.xml (UUID: )
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/share/python/archivematica-dashboard/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/share/python/archivematica-dashboard/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/share/python/archivematica-dashboard/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/share/python/archivematica-dashboard/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/share/archivematica/dashboard/main/management/commands/rebuild_transfer_backlog.py", line 76, in handle
    self.populate_index(es_client, transfer_backlog_dir)
  File "/usr/share/archivematica/dashboard/main/management/commands/rebuild_transfer_backlog.py", line 127, in populate_index
    transfer_uuid)
  File "/usr/share/archivematica/dashboard/main/management/commands/rebuild_transfer_backlog.py", line 137, in index_files
    status='backlog')
  File "/usr/lib/archivematica/archivematicaCommon/elasticSearchFunctions.py", line 521, in index_files
    status=status
  File "/usr/lib/archivematica/archivematicaCommon/elasticSearchFunctions.py", line 788, in index_transfer_files
    modification_date = f.modificationtime.strftime('%Y-%m-%d')
AttributeError: 'NoneType' object has no attribute 'strftime'
```

**Comment by sevein** [comment]
@mamedin can you give https://github.com/artefactual/archivematica/pull/987 a try?
